export enum BrokerImportTypes {
    Trading212 = 'Trading212',
    InteractiveBrokers = 'InteractiveBrokers',
    Xtb = 'Xtb',
    Etoro = 'Etoro',
    Revolut = 'Revolut',
    Anycoin = 'Anycoin',
    Degiro = 'Degiro',
    Portu = 'Portu',
    Coinbase = 'Coinbase',
    Binance = 'Binance',
    FioBanka = 'FioBanka',
    Patria = 'Patria',
    EtoroApi = 'EtoroApi',
    Lightyear = 'Lightyear',
    Freetrade = 'Freetrade',
    Schwab = 'Schwab',
}
