export interface YearCalculatedData {
    year: number;
    value: number;
    valueInterannually: number | null;
    transactionValue: number;
    transactionValueInterannually: number | null;
    gain: number;
    gainInterannually: number | null;
    gainPercentage: number;
    gainPercentageInterannually: number | null;
    gainPercentagePerAnnum: number;
    gainPercentagePerAnnumInterannually: number | null;
    realizedGain: number;
    realizedGainInterannually: number | null;
    dividendYield: number;
    dividendYieldInterannually: number | null;
    dividendYieldPercentage: number;
    dividendYieldPercentageInterannually: number | null;
    dividendYieldPercentagePerAnnum: number;
    dividendYieldPercentagePerAnnumInterannually: number | null;
    fxImpact: number;
    fxImpactInterannually: number | null;
    fxImpactPercentage: number;
    fxImpactPercentageInterannually: number | null;
    fxImpactPercentagePerAnnum: number;
    fxImpactPercentagePerAnnumInterannually: number | null;
    return: number;
    returnInterannually: number | null;
    returnPercentage: number;
    returnPercentageInterannually: number | null;
    returnPercentagePerAnnum: number;
    returnPercentagePerAnnumInterannually: number | null;
}
