version: '3.4'

services:
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        environment:
            PROXY_HOST: ${PROXY_HOST}
        ports:
            - "${PROXY_PORT}:80"
            - "${PROXY_PORT_SSL}:443"
        restart: unless-stopped
        networks:
            - frontend
            - backend
        volumes: 
            - ${PROXY_SSL_CERT}:/etc/nginx/ssl/server.pem:ro
            - ${PROXY_SSL_KEY}:/etc/nginx/ssl/server.key:ro

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on:
            - proxy
            - backend
        networks:
            - frontend

    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        environment:
            PROXY_HOST: ${PROXY_HOST}
            PROXY_PORT_SSL: ${PROXY_PORT_SSL}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            BACKEND_ROADRUNNER_WORKERS: ${BACKEND_ROADRUNNER_WORKERS}
            BACKEND_ROADRUNNER_DEBUG: ${BACKEND_ROADRUNNER_DEBUG}
            BACKEND_CORS_ALLOWED_ORIGIN: ${BACKEND_CORS_ALLOWED_ORIGIN}
            BACKEND_CORS_ALLOWED_HEADERS: ${BACKEND_CORS_ALLOWED_HEADERS}
            BACKEND_CORS_ALLOWED_METHODS: ${BACKEND_CORS_ALLOWED_METHODS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            AUTHORIZATION_TOKEN_KEY: ${AUTHORIZATION_TOKEN_KEY}
            ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
            EMAIL_FROM: ${EMAIL_FROM}
        depends_on:
            - proxy
            - db
        restart: unless-stopped
        networks:
            - backend
        volumes:
            - ./log:/app/log
            - ./backend/migrations:/app/migrations
            - ./backend:/app

    db:
        image: mariadb:11.2
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - backend
        volumes:
            - ./fingather_data:/var/lib/mysql

    rabbitmq:
        image: rabbitmq:3.12.12-alpine
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        networks:
            - backend
        volumes:
            - rabbitmq_volume:/var/lib/rabbitmq

    maildev:
        image: maildev/maildev:2.1.0
        restart: unless-stopped
        environment:
            MAILDEV_BASE_PATHNAME: /maildev
        networks:
            - backend

networks:
    frontend:
        name: frontend
    backend:
        name: backend

volumes:
    fingather_data:
        name: fingather_data
    rabbitmq_volume:
        name: rabbitmq_volume