services:
    proxy:
        build: 
            context: ./proxy
            dockerfile: Dockerfile
        environment:
            PROXY_HOST: ${PROXY_HOST}
        ports:
            - "${PROXY_PORT}:80"
            - "${PROXY_PORT_SSL}:443"
        restart: unless-stopped
        networks:
            - frontend
            - backend
        volumes: 
            - ${PROXY_SSL_CERT}:/etc/nginx/ssl/server.pem:ro
            - ${PROXY_SSL_KEY}:/etc/nginx/ssl/server.key:ro

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on:
            - proxy
            - backend
        restart: unless-stopped
        networks:
            - frontend
        volumes:
            - fingather_logos:/usr/share/nginx/html/images/logos

    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        environment:
            PROXY_HOST: ${PROXY_HOST}
            PROXY_PORT_SSL: ${PROXY_PORT_SSL}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            BACKEND_ROADRUNNER_WORKERS: ${BACKEND_ROADRUNNER_WORKERS}
            BACKEND_ROADRUNNER_DEBUG: ${BACKEND_ROADRUNNER_DEBUG}
            BACKEND_ROADRUNNER_JOB_WORKERS: ${BACKEND_ROADRUNNER_JOB_WORKERS}
            BACKEND_CORS_ALLOWED_ORIGIN: ${BACKEND_CORS_ALLOWED_ORIGIN}
            BACKEND_CORS_ALLOWED_HEADERS: ${BACKEND_CORS_ALLOWED_HEADERS}
            BACKEND_CORS_ALLOWED_METHODS: ${BACKEND_CORS_ALLOWED_METHODS}
            BACKEND_LOG_LEVEL: ${BACKEND_LOG_LEVEL}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
            MEMCACHED_HOST: ${MEMCACHED_HOST}
            MEMCACHED_PORT: ${MEMCACHED_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            SMTP_HOST: ${SMTP_HOST}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_USER: ${SMTP_USER}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            PROFILER_ENABLE: ${PROFILER_ENABLE}
            PROFILER_ENDPOINT: ${PROFILER_ENDPOINT}
            AUTHORIZATION_TOKEN_KEY: ${AUTHORIZATION_TOKEN_KEY}
            ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
            TWELVEDATA_API_KEY: ${TWELVEDATA_API_KEY}
            EMAIL_FROM: ${EMAIL_FROM}
        depends_on:
            - proxy
            - rabbitmq
            - memcached
            - redis
        restart: unless-stopped
        networks:
            - backend
        volumes:
            - fingather_logos:/app/public/images/logos
            - ./log:/app/log
            #- ./backend/migrations:/app/migrations
            #- ./backend/src:/app/src

    db:
        image: mariadb:11.4
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - backend
        volumes:
            - ./fingather_data:/var/lib/mysql
        profiles:
            - dev

    rabbitmq:
        image: rabbitmq:4.1.2-alpine
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        networks:
            - backend
        volumes:
            - rabbitmq_volume:/var/lib/rabbitmq

    memcached:
        image: memcached:1.6.38-alpine
        restart: unless-stopped
        networks:
            - backend

    redis:
        image: redis:8.0.3-alpine
        restart: unless-stopped
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        networks:
            - backend
        volumes:
            - redis_volume:/data

    adminer:
        image: adminer:5.3.0
        restart: unless-stopped
        networks:
            - frontend
            - backend

    buggregator:
        image: butschster/buggregator:1.13.2
        ports:
            - 127.0.0.1:8000:8000
            - 127.0.0.1:1025:1025
            - 127.0.0.1:9912:9912
            - 127.0.0.1:9913:9913
        networks:
            - backend
        profiles:
            - dev

networks:
    frontend:
        name: frontend
    backend:
        name: backend

volumes:
    fingather_data:
        name: fingather_data
    fingather_logos:
        name: fingather_logos
    rabbitmq_volume:
        name: rabbitmq_volume
    redis_volume:
        name: redis_volume