version: '3'

server:
    command: "php /app/src/rr-worker.php"

http:
    fcgi:
        address: tcp://0.0.0.0:9000
    middleware:
        - gzip
        - headers
    headers:
        cors:
            allowed_origin: ${BACKEND_CORS_ALLOWED_ORIGIN:-*}
            allowed_headers: ${BACKEND_CORS_ALLOWED_HEADERS:-*}
            allowed_methods: ${BACKEND_CORS_ALLOWED_METHODS:-GET,POST,PUT,DELETE,OPTIONS}

    pool:
        supervisor:
            watch_tick: 1s
            ttl: 1200s
            idle_ttl: 300s
            max_worker_memory: 256
        num_workers: ${BACKEND_ROADRUNNER_WORKERS:-10}
        debug: ${BACKEND_ROADRUNNER_DEBUG:-0}
        allocate_timeout: 10s

logs:
    mode: production
    level: error

amqp:
    addr: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}

jobs:
    consume: [ "email-verify", "api-import-prepare-check", "api-import-process-check", "user-warmup" ]
    pool:
        num_workers: ${BACKEND_ROADRUNNER_JOB_WORKERS:-5}
        supervisor:
            max_worker_memory: 256
    pipelines:
        email-verify:
            driver: amqp
            config:
                prefetch: 5
                priority: 1
                durable: true
                queue: email-verify
                routing_key: email-verify
        api-import-prepare-check:
            driver: amqp
            config:
                prefetch: 10
                priority: 2
                durable: true
                queue: api-import-prepare-check
                routing_key: api-import-prepare-check
        api-import-process-check:
            driver: amqp
            config:
                prefetch: 10
                priority: 3
                durable: true
                queue: api-import-process-check
                routing_key: api-import-process-check
        user-warmup:
            driver: amqp
            config:
                prefetch: 10
                priority: 4
                durable: true
                queue: user-warmup
                routing_key: user-warmup

rpc:
    listen: tcp://127.0.0.1:6001
