<?php

declare(strict_types=1);

namespace Migration;

use MarekSkopal\ORM\Migrations\Migration\Migration;

final class InitDataMigration extends Migration
{
	public function up(): void
	{
		$this->table('currencies')->insert([
			['id' => 1, 'code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 2, 'code' => 'EUR', 'name' => 'Euro', 'symbol' => '€', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 3, 'code' => 'GBP', 'name' => 'British Pound', 'symbol' => '£', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 5, 'code' => 'CZK', 'name' => 'Czech Crown', 'symbol' => 'Kč', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 6, 'code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => 'CA$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 7, 'code' => 'DKK', 'name' => 'Danish krone', 'symbol' => 'kr.', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 8, 'code' => 'NOK', 'name' => 'Norwegian krone', 'symbol' => 'kr', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 9, 'code' => 'SEK', 'name' => 'Swedish krona', 'symbol' => 'kr', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 10, 'code' => 'CHF', 'name' => 'Swiss franc', 'symbol' => 'fr.', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 11, 'code' => 'RUB', 'name' => 'Russian ruble', 'symbol' => '₽', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 12, 'code' => 'TRY', 'name' => 'Turkish lira', 'symbol' => '₺', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 13, 'code' => 'HUF', 'name' => 'Hungarian forint', 'symbol' => 'Ft', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 14, 'code' => 'ARS', 'name' => 'Argentine peso', 'symbol' => 'Arg$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 15, 'code' => 'BRL', 'name' => 'Brazilian real', 'symbol' => 'R$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 16, 'code' => 'CLP', 'name' => 'Chilean peso', 'symbol' => '$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 17, 'code' => 'MXN', 'name' => 'Mexican peso', 'symbol' => '$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 18, 'code' => 'PEN', 'name' => 'Peruvian sol', 'symbol' => 'S/', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 19, 'code' => 'AUD', 'name' => 'Australian dollar', 'symbol' => '$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 20, 'code' => 'CNY', 'name' => 'Renminbi', 'symbol' => '¥', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 21, 'code' => 'HKD', 'name' => 'Hong Kong dollar', 'symbol' => 'HK$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 22, 'code' => 'INR', 'name' => 'Indian rupee', 'symbol' => '₹', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 23, 'code' => 'IDR', 'name' => 'Indonesian rupee', 'symbol' => 'Rp', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 24, 'code' => 'ILS', 'name' => 'Israeli new shekel', 'symbol' => '₪', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 26, 'code' => 'JPY', 'name' => 'Japanese yen', 'symbol' => '¥', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 27, 'code' => 'MYR', 'name' => 'Malaysian ringgit', 'symbol' => 'RM', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 28, 'code' => 'QAR', 'name' => 'Qatari riyal', 'symbol' => 'QR', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 29, 'code' => 'SAR', 'name' => 'Saudi riyal', 'symbol' => 'SR', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 30, 'code' => 'SGD', 'name' => 'Singapore dollar', 'symbol' => 'S$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 31, 'code' => 'KRW', 'name' => 'South Korean won', 'symbol' => '₩', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 32, 'code' => 'TWD', 'name' => 'New Taiwan dollar', 'symbol' => 'NT$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 33, 'code' => 'THB', 'name' => 'Thai baht', 'symbol' => '฿', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 34, 'code' => 'AED', 'name' => 'United Arab Emirates dirham', 'symbol' => 'Dh', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 35, 'code' => 'EGP', 'name' => 'Egyptian pound', 'symbol' => 'E£', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 36, 'code' => 'EGP', 'name' => 'South African rand', 'symbol' => 'R', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
			['id' => 38, 'code' => 'NZD', 'name' => 'New Zealand dollar', 'symbol' => '$', 'multiply_currency_id' => null, 'multiplier' => 1, 'is_selectable' => true],
		]);

		$this->table('currencies')->insert([
			['id' => 4, 'code' => 'GBX', 'name' => 'British Pound (penny)', 'symbol' => 'p', 'multiply_currency_id' => 3, 'multiplier' => 100, 'is_selectable' => false],
			['id' => 25, 'code' => 'ILA', 'name' => 'Israeli new shekel (agora)', 'symbol' => 'a', 'multiply_currency_id' => 24, 'multiplier' => 100, 'is_selectable' => false],
			['id' => 37, 'code' => 'EGP', 'name' => 'South African rand (cent)', 'symbol' => 'c', 'multiply_currency_id' => 36, 'multiplier' => 100, 'is_selectable' => false],
		]);

		$this->table('users')->insert([
			['id' => 1, 'email' => 'admin@fingather.com', 'password' => '$2y$10$Gv6vVjtQsz2n/1zk.wbyKOOON7ThrnpzJ0U7xJAUNHSE.4dJSyvSS', 'name' => 'FinGather Admin', 'default_currency_id' => 5, 'role' => 'Admin'],
		]);

		$this->table('portfolios')->insert([
			['id' => 1, 'user_id' => 1, 'name' => 'My Portfolio', 'is_default' => true],
		]);

		$this->table('markets')->insert([
			['id' => 1, 'type' => 'Stock', 'name' => 'NASDAQ Stock Exchange', 'acronym' => 'NASDAQ', 'mic' => 'XNAS', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => ''],
			['id' => 2, 'type' => 'Stock', 'name' => 'NASDAQ Stock Exchange', 'acronym' => 'NASDAQ', 'mic' => 'XNMS', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'UQ'],
			['id' => 3, 'type' => 'Stock', 'name' => 'NASDAQ Stock Exchange', 'acronym' => 'NASDAQ', 'mic' => 'XNGS', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'UW'],
			['id' => 4, 'type' => 'Stock', 'name' => 'NASDAQ Stock Exchange', 'acronym' => 'NASDAQ', 'mic' => 'XNCM', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'UR'],
			['id' => 5, 'type' => 'Stock', 'name' => 'New York Stock Exchange', 'acronym' => 'NYSE', 'mic' => 'XNYS', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'UN'],
			['id' => 6, 'type' => 'Stock', 'name' => 'New York Stock Exchange', 'acronym' => 'NYSE', 'mic' => 'XASE', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'UA'],
			['id' => 7, 'type' => 'Stock', 'name' => 'New York Stock Exchange', 'acronym' => 'NYSE', 'mic' => 'ARCX', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'UP'],
			['id' => 8, 'type' => 'Stock', 'name' => 'OTC Markets', 'acronym' => 'OTC', 'mic' => 'PSGM', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'PQ'],
			['id' => 9, 'type' => 'Stock', 'name' => 'OTC Markets', 'acronym' => 'OTC', 'mic' => 'EXPM', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'PQ'],
			['id' => 10, 'type' => 'Stock', 'name' => 'OTC Markets', 'acronym' => 'OTC', 'mic' => 'PINX', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'PQ'],
			['id' => 11, 'type' => 'Stock', 'name' => 'OTC Markets', 'acronym' => 'OTC', 'mic' => 'OTCB', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'PQ'],
			['id' => 12, 'type' => 'Stock', 'name' => 'OTC Markets', 'acronym' => 'OTC', 'mic' => 'OTCQ', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'PQ'],
			['id' => 13, 'type' => 'Stock', 'name' => 'Chicago Board Options Exchange', 'acronym' => 'CBOE', 'mic' => 'BATS', 'country' => 'US', 'city' => 'Chicago', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => 'UF'],
			['id' => 14, 'type' => 'Stock', 'name' => 'New York Board of Trade', 'acronym' => 'ICE', 'mic' => 'NYBOT', 'country' => 'US', 'city' => 'New York', 'timezone' => 'America/New_York', 'currency_id' => 1, 'exchange_code' => ''],
			['id' => 15, 'type' => 'Stock', 'name' => 'London Stock Exchange', 'acronym' => 'LSE', 'mic' => 'XLON', 'country' => 'GB', 'city' => 'London', 'timezone' => 'Europe/London', 'currency_id' => 3, 'exchange_code' => 'LN'],
			['id' => 16, 'type' => 'Stock', 'name' => 'Euronext Paris', 'acronym' => 'EURONEXT', 'mic' => 'XPAR', 'country' => 'FR', 'city' => 'Paris', 'timezone' => 'Europe/Paris', 'currency_id' => 2, 'exchange_code' => 'FP'],
			['id' => 17, 'type' => 'Stock', 'name' => 'Euronext Brussels', 'acronym' => 'EURONEXT', 'mic' => 'XBRU', 'country' => 'BE', 'city' => 'Brussels', 'timezone' => 'Europe/Brussels', 'currency_id' => 2, 'exchange_code' => 'BB'],
			['id' => 18, 'type' => 'Stock', 'name' => 'Euronext Amsterdam', 'acronym' => 'EURONEXT', 'mic' => 'XAMS', 'country' => 'NL', 'city' => 'Amsterdam', 'timezone' => 'Europe/Amsterdam', 'currency_id' => 2, 'exchange_code' => 'NA'],
			['id' => 19, 'type' => 'Stock', 'name' => 'Euronext Lisbon', 'acronym' => 'EURONEXT', 'mic' => 'XLIS', 'country' => 'PT', 'city' => 'Lisbon', 'timezone' => 'Europe/Lisbon', 'currency_id' => 2, 'exchange_code' => 'PL'],
			['id' => 20, 'type' => 'Stock', 'name' => 'Frankfurt Stock Exchange', 'acronym' => 'FSX', 'mic' => 'XFRA', 'country' => 'DE', 'city' => 'Frankfurt', 'timezone' => 'Europe/Berlin', 'currency_id' => 2, 'exchange_code' => 'GF'],
			['id' => 21, 'type' => 'Stock', 'name' => 'Berlin Stock Exchange', 'acronym' => 'XBER', 'mic' => 'XBER', 'country' => 'DE', 'city' => 'Berlin', 'timezone' => 'Europe/Berlin', 'currency_id' => 2, 'exchange_code' => 'GB'],
			['id' => 22, 'type' => 'Stock', 'name' => 'Munich Stock Exchange', 'acronym' => 'XMUN', 'mic' => 'XMUN', 'country' => 'DE', 'city' => 'Munich', 'timezone' => 'Europe/Berlin', 'currency_id' => 2, 'exchange_code' => 'GM'],
			['id' => 23, 'type' => 'Stock', 'name' => 'Stuttgart Stock Exchange', 'acronym' => 'XSTU', 'mic' => 'XMUN', 'country' => 'DE', 'city' => 'Stuttgart', 'timezone' => 'Europe/Berlin', 'currency_id' => 2, 'exchange_code' => 'GS'],
			['id' => 24, 'type' => 'Stock', 'name' => 'Deutsche Börse Xetra', 'acronym' => 'XETR', 'mic' => 'XETR', 'country' => 'DE', 'city' => 'Frankfurt', 'timezone' => 'Europe/Berlin', 'currency_id' => 2, 'exchange_code' => 'GY'],
			['id' => 25, 'type' => 'Stock', 'name' => 'Hanover Stock Exchange', 'acronym' => 'XHAN', 'mic' => 'XHAN', 'country' => 'DE', 'city' => 'Hanover', 'timezone' => 'Europe/Berlin', 'currency_id' => 2, 'exchange_code' => 'GI'],
			['id' => 26, 'type' => 'Stock', 'name' => 'Dusseldorf Stock Exchange', 'acronym' => 'XDUS', 'mic' => 'XDUS', 'country' => 'DE', 'city' => 'Dusseldorf', 'timezone' => 'Europe/Berlin', 'currency_id' => 2, 'exchange_code' => 'GD'],
			['id' => 27, 'type' => 'Stock', 'name' => 'Hamburg Stock Exchange', 'acronym' => 'XHAM', 'mic' => 'XDUS', 'country' => 'DE', 'city' => 'Hamburg', 'timezone' => 'Europe/Berlin', 'currency_id' => 2, 'exchange_code' => 'GH'],
			['id' => 28, 'type' => 'Stock', 'name' => 'Vienna Stock Exchange', 'acronym' => 'VSE', 'mic' => 'XWBO', 'country' => 'AT', 'city' => 'Vienna', 'timezone' => 'Europe/Vienna', 'currency_id' => 2, 'exchange_code' => 'AV'],
			['id' => 29, 'type' => 'Stock', 'name' => 'Helsinki Stock Exchange', 'acronym' => 'OMXH', 'mic' => 'XHEL', 'country' => 'FI', 'city' => 'Helsinki', 'timezone' => 'Europe/Helsinki', 'currency_id' => 2, 'exchange_code' => 'FH'],
			['id' => 30, 'type' => 'Stock', 'name' => 'Irish Stock Exchange', 'acronym' => 'ISE', 'mic' => 'XDUB', 'country' => 'IE', 'city' => 'Dublin', 'timezone' => 'Europe/Dublin', 'currency_id' => 2, 'exchange_code' => 'ID'],
			['id' => 31, 'type' => 'Stock', 'name' => 'Euronext Growth Dublin', 'acronym' => 'XESM', 'mic' => 'XESM', 'country' => 'IE', 'city' => 'Dublin', 'timezone' => 'Europe/Dublin', 'currency_id' => 2, 'exchange_code' => ''],
			['id' => 32, 'type' => 'Stock', 'name' => 'Euronext Dublin', 'acronym' => 'XMSM', 'mic' => 'XMSM', 'country' => 'IE', 'city' => 'Dublin', 'timezone' => 'Europe/Dublin', 'currency_id' => 2, 'exchange_code' => ''],
			['id' => 33, 'type' => 'Stock', 'name' => 'Italian Stock Exchange in Milan', 'acronym' => 'MTA', 'mic' => 'XMIL', 'country' => 'IT', 'city' => 'Milan', 'timezone' => 'Europe/Rome', 'currency_id' => 2, 'exchange_code' => 'IM'],
			['id' => 34, 'type' => 'Stock', 'name' => 'Oslo Stock Exchange', 'acronym' => 'OSE', 'mic' => 'XOSL', 'country' => 'NO', 'city' => 'Oslo', 'timezone' => 'Europe/Oslo', 'currency_id' => 8, 'exchange_code' => 'NO'],
			['id' => 35, 'type' => 'Stock', 'name' => 'Madrid Stock Exchange', 'acronym' => 'BME', 'mic' => 'XMAD', 'country' => 'ES', 'city' => 'Madrid', 'timezone' => 'Europe/Madrid', 'currency_id' => 2, 'exchange_code' => 'SN'],
			['id' => 36, 'type' => 'Stock', 'name' => 'Nasdaq Stockholm', 'acronym' => 'OMX', 'mic' => 'XSTO', 'country' => 'SE', 'city' => 'Stockholm', 'timezone' => 'Europe/Stockholm', 'currency_id' => 9, 'exchange_code' => 'SS'],
			['id' => 37, 'type' => 'Stock', 'name' => 'First North Sweden', 'acronym' => 'SSME', 'mic' => 'SSME', 'country' => 'SE', 'city' => 'Stockholm', 'timezone' => 'Europe/Stockholm', 'currency_id' => 9, 'exchange_code' => 'SF'],
			['id' => 38, 'type' => 'Stock', 'name' => 'Spotlight Stock Market', 'acronym' => 'SSM', 'mic' => 'XSAT', 'country' => 'SE', 'city' => 'Stockholm', 'timezone' => 'Europe/Stockholm', 'currency_id' => 9, 'exchange_code' => 'NO'],
			['id' => 39, 'type' => 'Stock', 'name' => 'SIX Swiss Exchange', 'acronym' => 'SIX', 'mic' => 'XSWX', 'country' => 'CH', 'city' => 'Zurich', 'timezone' => 'Europe/Zurich', 'currency_id' => 10, 'exchange_code' => 'KA'],
			['id' => 40, 'type' => 'Stock', 'name' => 'Moscow Exchange', 'acronym' => 'MOEX', 'mic' => 'MISX', 'country' => 'RU', 'city' => 'Moscow', 'timezone' => 'Europe/Moscow', 'currency_id' => 11, 'exchange_code' => 'RR'],
			['id' => 41, 'type' => 'Stock', 'name' => 'Istanbul Stock Exchange', 'acronym' => 'BIST', 'mic' => 'XIST', 'country' => 'TR', 'city' => 'Istanbul', 'timezone' => 'Europe/Istanbul', 'currency_id' => 12, 'exchange_code' => 'TS'],
			['id' => 42, 'type' => 'Stock', 'name' => 'Nasdaq Copenhagen', 'acronym' => 'OMXC', 'mic' => 'XCSE', 'country' => 'DK', 'city' => 'Copenhagen', 'timezone' => 'Europe/Copenhagen', 'currency_id' => 7, 'exchange_code' => 'DF'],
			['id' => 43, 'type' => 'Stock', 'name' => 'First North Denmark', 'acronym' => 'DSME', 'mic' => 'DSME', 'country' => 'DK', 'city' => 'Copenhagen', 'timezone' => 'Europe/Copenhagen', 'currency_id' => 7, 'exchange_code' => ''],
			['id' => 44, 'type' => 'Stock', 'name' => 'Nasdaq Tallinn', 'acronym' => 'OMXT', 'mic' => 'XTAL', 'country' => 'EE', 'city' => 'Tallinn', 'timezone' => 'Europe/Tallinn', 'currency_id' => 2, 'exchange_code' => 'ET'],
			['id' => 45, 'type' => 'Stock', 'name' => 'Athens Stock Exchange', 'acronym' => 'ASE', 'mic' => 'ASEX', 'country' => 'GR', 'city' => 'Athens', 'timezone' => 'Europe/Athens', 'currency_id' => 2, 'exchange_code' => 'XT'],
			['id' => 46, 'type' => 'Stock', 'name' => 'Prague Stock Exchange', 'acronym' => 'PSE', 'mic' => 'XPRA', 'country' => 'CZ', 'city' => 'Prague', 'timezone' => 'Europe/Prague', 'currency_id' => 5, 'exchange_code' => 'CK'],
			['id' => 47, 'type' => 'Stock', 'name' => 'Budapest Stock Exchange', 'acronym' => 'BSE', 'mic' => 'XBUD', 'country' => 'HU', 'city' => 'Budapest', 'timezone' => 'Europe/Budapest', 'currency_id' => 13, 'exchange_code' => 'HB'],
			['id' => 48, 'type' => 'Stock', 'name' => 'Nasdaq Riga', 'acronym' => 'OMXR', 'mic' => 'XRIS', 'country' => 'LV', 'city' => 'Riga', 'timezone' => 'Europe/Riga', 'currency_id' => 2, 'exchange_code' => 'LG'],
			['id' => 49, 'type' => 'Stock', 'name' => 'Nasdaq Vilnius', 'acronym' => 'OMXV', 'mic' => 'XLIT', 'country' => 'LT', 'city' => 'Vilnius', 'timezone' => 'Europe/Vilnius', 'currency_id' => 2, 'exchange_code' => 'LH'],
			['id' => 50, 'type' => 'Stock', 'name' => 'Canadian Securities Exchange', 'acronym' => 'CSE', 'mic' => 'XCNQ', 'country' => 'CA', 'city' => 'Toronto', 'timezone' => 'America/Toronto', 'currency_id' => 6, 'exchange_code' => 'CF'],
			['id' => 51, 'type' => 'Stock', 'name' => 'NEO Exchange', 'acronym' => 'NEO', 'mic' => 'NEOE', 'country' => 'CA', 'city' => 'Toronto', 'timezone' => 'America/Toronto', 'currency_id' => 6, 'exchange_code' => 'QF'],
			['id' => 52, 'type' => 'Stock', 'name' => 'Toronto Stock Exchange', 'acronym' => 'TSX', 'mic' => 'XTSE', 'country' => 'CA', 'city' => 'Toronto', 'timezone' => 'America/Toronto', 'currency_id' => 6, 'exchange_code' => 'CT'],
			['id' => 53, 'type' => 'Stock', 'name' => 'TSX Venture Exchange', 'acronym' => 'TSXV', 'mic' => 'XTSX', 'country' => 'CA', 'city' => 'Toronto', 'timezone' => 'America/Toronto', 'currency_id' => 6, 'exchange_code' => 'CV'],
			['id' => 54, 'type' => 'Stock', 'name' => 'Buenos Aires Stock Exchange', 'acronym' => 'BCBA', 'mic' => 'XBUE', 'country' => 'AR', 'city' => 'Buenos Aires', 'timezone' => 'America/Argentina/Buenos_Aires', 'currency_id' => 14, 'exchange_code' => 'AF'],
			['id' => 55, 'type' => 'Stock', 'name' => 'B3 Stock Exchange', 'acronym' => 'Bovespa', 'mic' => 'BVMF', 'country' => 'BR', 'city' => 'São Paulo', 'timezone' => 'America/Paramaribo', 'currency_id' => 15, 'exchange_code' => 'BS'],
			['id' => 56, 'type' => 'Stock', 'name' => 'Santiago Stock Exchange', 'acronym' => 'SSE', 'mic' => 'XSGO', 'country' => 'CL', 'city' => 'Santiago', 'timezone' => 'America/Santiago', 'currency_id' => 16, 'exchange_code' => 'CC'],
			['id' => 57, 'type' => 'Stock', 'name' => 'Mexican Stock Exchange', 'acronym' => 'BMV', 'mic' => 'XMEX', 'country' => 'MX', 'city' => 'Mexico City', 'timezone' => 'America/Mexico_City', 'currency_id' => 17, 'exchange_code' => 'MM'],
			['id' => 58, 'type' => 'Stock', 'name' => 'Lima Stock Exchange', 'acronym' => 'BVL', 'mic' => 'XLIM', 'country' => 'PE', 'city' => 'Lima', 'timezone' => 'America/Lima', 'currency_id' => 18, 'exchange_code' => 'PE'],
			['id' => 59, 'type' => 'Stock', 'name' => 'CBOE Australia', 'acronym' => 'CXA', 'mic' => 'CXAC', 'country' => 'AU', 'city' => 'Sydney', 'timezone' => 'Australia/Sydney', 'currency_id' => 19, 'exchange_code' => ''],
			['id' => 60, 'type' => 'Stock', 'name' => 'Australia Stock Exchange', 'acronym' => 'ASX', 'mic' => 'XASX', 'country' => 'AU', 'city' => 'Sydney', 'timezone' => 'Australia/Sydney', 'currency_id' => 19, 'exchange_code' => 'AT'],
			['id' => 61, 'type' => 'Stock', 'name' => 'Shenzhen Stock Exchange', 'acronym' => 'SZSE', 'mic' => 'XSHE', 'country' => 'CN', 'city' => 'Shenzhen', 'timezone' => 'Asia/Shanghai', 'currency_id' => 20, 'exchange_code' => 'CS'],
			['id' => 62, 'type' => 'Stock', 'name' => 'Shanghai Stock Exchange', 'acronym' => 'SSE', 'mic' => 'XSHG', 'country' => 'CN', 'city' => 'Shanghai', 'timezone' => 'Asia/Shanghai', 'currency_id' => 20, 'exchange_code' => 'CG'],
			['id' => 63, 'type' => 'Stock', 'name' => 'Hong Kong Stock Exchange', 'acronym' => 'HKEX', 'mic' => 'XHKG', 'country' => 'HK', 'city' => 'Hong Kong', 'timezone' => 'Asia/Hong_Kong', 'currency_id' => 21, 'exchange_code' => 'HK'],
			['id' => 64, 'type' => 'Stock', 'name' => 'Bombay Stock Exchange', 'acronym' => 'BSE', 'mic' => 'XBOM', 'country' => 'IN', 'city' => 'Mumbai', 'timezone' => 'Asia/Kolkata', 'currency_id' => 22, 'exchange_code' => 'IB'],
			['id' => 65, 'type' => 'Stock', 'name' => 'India National Stock Exchange', 'acronym' => 'NSE', 'mic' => 'XNSE', 'country' => 'IN', 'city' => 'Mumbai', 'timezone' => 'Asia/Kolkata', 'currency_id' => 22, 'exchange_code' => 'IS'],
			['id' => 66, 'type' => 'Stock', 'name' => 'Indonesia Stock Exchange', 'acronym' => 'IDX', 'mic' => 'XIDX', 'country' => 'ID', 'city' => 'Jakarta', 'timezone' => 'Asia/Jakarta', 'currency_id' => 23, 'exchange_code' => 'IJ'],
			['id' => 67, 'type' => 'Stock', 'name' => 'Tel Aviv Stock Exchange', 'acronym' => 'TASE', 'mic' => 'XTAE', 'country' => 'IL', 'city' => 'Tel Aviv', 'timezone' => 'Asia/Jerusalem', 'currency_id' => 25, 'exchange_code' => 'IT'],
			['id' => 68, 'type' => 'Stock', 'name' => 'Japan Exchange Group', 'acronym' => 'JPX', 'mic' => 'XJPX', 'country' => 'JP', 'city' => 'Tokyo', 'timezone' => 'Asia/Tokyo', 'currency_id' => 26, 'exchange_code' => 'JT'],
			['id' => 69, 'type' => 'Stock', 'name' => 'Sapporo Securities Exchange', 'acronym' => 'XSAP', 'mic' => 'XSAP', 'country' => 'JP', 'city' => 'Sapporo', 'timezone' => 'Asia/Tokyo', 'currency_id' => 26, 'exchange_code' => 'JS'],
			['id' => 70, 'type' => 'Stock', 'name' => 'Bursa Malaysia', 'acronym' => 'MYX', 'mic' => 'XKLS', 'country' => 'MY', 'city' => 'Kuala Lumpur', 'timezone' => 'Asia/Kuala_Lumpur', 'currency_id' => 27, 'exchange_code' => 'MK'],
			['id' => 71, 'type' => 'Stock', 'name' => 'Qatar Exchange', 'acronym' => 'QE', 'mic' => 'DSMD', 'country' => 'QA', 'city' => 'Doha', 'timezone' => 'Asia/Qatar', 'currency_id' => 28, 'exchange_code' => 'QD'],
			['id' => 72, 'type' => 'Stock', 'name' => 'Saudi Stock Exchange', 'acronym' => 'SSE', 'mic' => 'XSAU', 'country' => 'SA', 'city' => 'Rijad', 'timezone' => 'Asia/Riyadh', 'currency_id' => 29, 'exchange_code' => 'AB'],
			['id' => 73, 'type' => 'Stock', 'name' => 'Singapore Exchange', 'acronym' => 'SGX', 'mic' => 'XSES', 'country' => 'SG', 'city' => 'Singapore', 'timezone' => 'Asia/Singapore', 'currency_id' => 30, 'exchange_code' => 'SP'],
			['id' => 74, 'type' => 'Stock', 'name' => 'Korea Exchange (Stock Market)', 'acronym' => 'KRX', 'mic' => 'XKRX', 'country' => 'KR', 'city' => 'Seoul', 'timezone' => 'Asia/Seoul', 'currency_id' => 31, 'exchange_code' => 'KP'],
			['id' => 75, 'type' => 'Stock', 'name' => 'Korea Exchange (Kosdaq)', 'acronym' => 'KOSDAQ', 'mic' => 'XKOS', 'country' => 'KR', 'city' => 'Seoul', 'timezone' => 'Asia/Seoul', 'currency_id' => 31, 'exchange_code' => 'KQ'],
			['id' => 76, 'type' => 'Stock', 'name' => 'Korea New Exchange', 'acronym' => 'KONEX', 'mic' => 'XKON', 'country' => 'KR', 'city' => 'Seoul', 'timezone' => 'Asia/Seoul', 'currency_id' => 31, 'exchange_code' => 'KE'],
			['id' => 77, 'type' => 'Stock', 'name' => 'Taiwan Stock Exchange', 'acronym' => 'TWSE', 'mic' => 'XTAI', 'country' => 'TW', 'city' => 'Taipei', 'timezone' => 'Asia/Taipei', 'currency_id' => 32, 'exchange_code' => 'TT'],
			['id' => 78, 'type' => 'Stock', 'name' => 'Stock Exchange of Thailand', 'acronym' => 'SET', 'mic' => 'XBKK', 'country' => 'TH', 'city' => 'Bangkok', 'timezone' => 'Asia/Bangkok', 'currency_id' => 33, 'exchange_code' => 'TB'],
			['id' => 79, 'type' => 'Stock', 'name' => 'Abu Dhabi Securities Exchange', 'acronym' => 'ADX', 'mic' => 'XADS', 'country' => 'AE', 'city' => 'Abu Dhabi', 'timezone' => 'Asia/Dubai', 'currency_id' => 34, 'exchange_code' => 'DH'],
			['id' => 80, 'type' => 'Stock', 'name' => 'Egyptian Exchange', 'acronym' => 'EGX', 'mic' => 'XCAI', 'country' => 'EG', 'city' => 'Cairo', 'timezone' => 'Africa/Cairo', 'currency_id' => 35, 'exchange_code' => 'EC'],
			['id' => 81, 'type' => 'Stock', 'name' => 'Johannesburg Stock Exchange', 'acronym' => 'JSE', 'mic' => 'XJSE', 'country' => 'ZA', 'city' => 'Johannesburg', 'timezone' => 'Africa/Johannesburg', 'currency_id' => 37, 'exchange_code' => 'SJ'],
			['id' => 82, 'type' => 'Stock', 'name' => 'New Zealand Exchange Ltd', 'acronym' => 'NZX', 'mic' => 'XNZE', 'country' => 'NZ', 'city' => 'Wellington', 'timezone' => 'Pacific/Auckland', 'currency_id' => 38, 'exchange_code' => 'NZ'],

			['id' => 83, 'type' => 'Crypto', 'name' => 'Binance', 'acronym' => '', 'mic' => 'Bina', 'country' => '', 'city' => '', 'web' => '', 'currency_id' => 1, 'exchange_code' => ''],

		]);

		$this->table('brokers')->insert([
			['id' => 1, 'user_id' => 1, 'portfolio_id' => 1, 'name' => 'Trading212', 'import_type' => 'Trading212'],
			['id' => 2, 'user_id' => 1, 'portfolio_id' => 1, 'name' => 'Revolut', 'import_type' => 'Revolut'],
			['id' => 3, 'user_id' => 1, 'portfolio_id' => 1, 'name' => 'Anycoin', 'import_type' => 'Anycoin'],
		]);

		$this->table('groups')->insert([
			['id' => 1, 'user_id' => 1, 'portfolio_id' => 1, 'name' => 'Others', 'color' => '#2c3d3f', 'is_others' => true],
		]);

		$this->table('countries')->insert([
			['id' => 1, 'iso_code' => 'AF', 'iso_code3' => 'AFG', 'name' => 'Afghanistan', 'is_others' => false],
			['id' => 2, 'iso_code' => 'AL', 'iso_code3' => 'ALB', 'name' => 'Albania', 'is_others' => false],
			['id' => 3, 'iso_code' => 'DZ', 'iso_code3' => 'DZA', 'name' => 'Algeria', 'is_others' => false],
			['id' => 4, 'iso_code' => 'AS', 'iso_code3' => 'ASM', 'name' => 'American Samoa', 'is_others' => false],
			['id' => 5, 'iso_code' => 'AD', 'iso_code3' => 'AND', 'name' => 'Andorra', 'is_others' => false],
			['id' => 6, 'iso_code' => 'AO', 'iso_code3' => 'AGO', 'name' => 'Angola', 'is_others' => false],
			['id' => 7, 'iso_code' => 'AI', 'iso_code3' => 'AIA', 'name' => 'Anguilla', 'is_others' => false],
			['id' => 8, 'iso_code' => 'AQ', 'iso_code3' => 'ATA', 'name' => 'Antarctica', 'is_others' => false],
			['id' => 9, 'iso_code' => 'AG', 'iso_code3' => 'ATG', 'name' => 'Antigua and Barbuda', 'is_others' => false],
			['id' => 10, 'iso_code' => 'AR', 'iso_code3' => 'ARG', 'name' => 'Argentina', 'is_others' => false],
			['id' => 11, 'iso_code' => 'AM', 'iso_code3' => 'ARM', 'name' => 'Armenia', 'is_others' => false],
			['id' => 12, 'iso_code' => 'AW', 'iso_code3' => 'ABW', 'name' => 'Aruba', 'is_others' => false],
			['id' => 13, 'iso_code' => 'AU', 'iso_code3' => 'AUS', 'name' => 'Australia', 'is_others' => false],
			['id' => 14, 'iso_code' => 'AT', 'iso_code3' => 'AUT', 'name' => 'Austria', 'is_others' => false],
			['id' => 15, 'iso_code' => 'AZ', 'iso_code3' => 'AZE', 'name' => 'Azerbaijan', 'is_others' => false],
			['id' => 16, 'iso_code' => 'BS', 'iso_code3' => 'BHS', 'name' => 'Bahamas', 'is_others' => false],
			['id' => 17, 'iso_code' => 'BH', 'iso_code3' => 'BHR', 'name' => 'Bahrain', 'is_others' => false],
			['id' => 18, 'iso_code' => 'BD', 'iso_code3' => 'BGD', 'name' => 'Bangladesh', 'is_others' => false],
			['id' => 19, 'iso_code' => 'BB', 'iso_code3' => 'BRB', 'name' => 'Barbados', 'is_others' => false],
			['id' => 20, 'iso_code' => 'BY', 'iso_code3' => 'BLR', 'name' => 'Belarus', 'is_others' => false],
			['id' => 21, 'iso_code' => 'BE', 'iso_code3' => 'BEL', 'name' => 'Belgium', 'is_others' => false],
			['id' => 22, 'iso_code' => 'BZ', 'iso_code3' => 'BLZ', 'name' => 'Belize', 'is_others' => false],
			['id' => 23, 'iso_code' => 'BJ', 'iso_code3' => 'BEN', 'name' => 'Benin', 'is_others' => false],
			['id' => 24, 'iso_code' => 'BM', 'iso_code3' => 'BMU', 'name' => 'Bermuda', 'is_others' => false],
			['id' => 25, 'iso_code' => 'BT', 'iso_code3' => 'BTN', 'name' => 'Bhutan', 'is_others' => false],
			['id' => 26, 'iso_code' => 'BO', 'iso_code3' => 'BOL', 'name' => 'Bolivia', 'is_others' => false],
			['id' => 27, 'iso_code' => 'BA', 'iso_code3' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'is_others' => false],
			['id' => 28, 'iso_code' => 'BW', 'iso_code3' => 'BWA', 'name' => 'Botswana', 'is_others' => false],
			['id' => 29, 'iso_code' => 'BV', 'iso_code3' => 'BVT', 'name' => 'Bouvet Island', 'is_others' => false],
			['id' => 30, 'iso_code' => 'BR', 'iso_code3' => 'BRA', 'name' => 'Brazil', 'is_others' => false],
			['id' => 31, 'iso_code' => 'IO', 'iso_code3' => 'IOT', 'name' => 'British Indian Ocean Territory', 'is_others' => false],
			['id' => 32, 'iso_code' => 'BN', 'iso_code3' => 'BRN', 'name' => 'Brunei Darussalam', 'is_others' => false],
			['id' => 33, 'iso_code' => 'BG', 'iso_code3' => 'BGR', 'name' => 'Bulgaria', 'is_others' => false],
			['id' => 34, 'iso_code' => 'BF', 'iso_code3' => 'BFA', 'name' => 'Burkina Faso', 'is_others' => false],
			['id' => 35, 'iso_code' => 'BI', 'iso_code3' => 'BDI', 'name' => 'Burundi', 'is_others' => false],
			['id' => 36, 'iso_code' => 'KH', 'iso_code3' => 'KHM', 'name' => 'Cambodia', 'is_others' => false],
			['id' => 37, 'iso_code' => 'CM', 'iso_code3' => 'CMR', 'name' => 'Cameroon', 'is_others' => false],
			['id' => 38, 'iso_code' => 'CA', 'iso_code3' => 'CAN', 'name' => 'Canada', 'is_others' => false],
			['id' => 39, 'iso_code' => 'CV', 'iso_code3' => 'CPV', 'name' => 'Cape Verde', 'is_others' => false],
			['id' => 40, 'iso_code' => 'KY', 'iso_code3' => 'CYM', 'name' => 'Cayman Islands', 'is_others' => false],
			['id' => 41, 'iso_code' => 'CF', 'iso_code3' => 'CAF', 'name' => 'Central African Republic', 'is_others' => false],
			['id' => 42, 'iso_code' => 'TD', 'iso_code3' => 'TCD', 'name' => 'Chad', 'is_others' => false],
			['id' => 43, 'iso_code' => 'CL', 'iso_code3' => 'CHL', 'name' => 'Chile', 'is_others' => false],
			['id' => 44, 'iso_code' => 'CN', 'iso_code3' => 'CHN', 'name' => 'China', 'is_others' => false],
			['id' => 45, 'iso_code' => 'CX', 'iso_code3' => 'CXR', 'name' => 'Christmas Island', 'is_others' => false],
			['id' => 46, 'iso_code' => 'CC', 'iso_code3' => 'CCK', 'name' => 'Cocos (Keeling) Islands', 'is_others' => false],
			['id' => 47, 'iso_code' => 'CO', 'iso_code3' => 'COL', 'name' => 'Colombia', 'is_others' => false],
			['id' => 48, 'iso_code' => 'KM', 'iso_code3' => 'COM', 'name' => 'Comoros', 'is_others' => false],
			['id' => 49, 'iso_code' => 'CG', 'iso_code3' => 'COG', 'name' => 'Congo', 'is_others' => false],
			['id' => 50, 'iso_code' => 'CD', 'iso_code3' => 'COD', 'name' => 'Congo, The Democratic Republic of the', 'is_others' => false],
			['id' => 51, 'iso_code' => 'CK', 'iso_code3' => 'COK', 'name' => 'Cook Islands', 'is_others' => false],
			['id' => 52, 'iso_code' => 'CR', 'iso_code3' => 'CRI', 'name' => 'Costa Rica', 'is_others' => false],
			['id' => 53, 'iso_code' => 'CI', 'iso_code3' => 'CIV', 'name' => 'Cote d\'Ivoire', 'is_others' => false],
			['id' => 54, 'iso_code' => 'HR', 'iso_code3' => 'HRV', 'name' => 'Croatia', 'is_others' => false],
			['id' => 55, 'iso_code' => 'CU', 'iso_code3' => 'CUB', 'name' => 'Cuba', 'is_others' => false],
			['id' => 56, 'iso_code' => 'CY', 'iso_code3' => 'CYP', 'name' => 'Cyprus', 'is_others' => false],
			['id' => 57, 'iso_code' => 'CZ', 'iso_code3' => 'CZE', 'name' => 'Czech Republic', 'is_others' => false],
			['id' => 58, 'iso_code' => 'DK', 'iso_code3' => 'DNK', 'name' => 'Denmark', 'is_others' => false],
			['id' => 59, 'iso_code' => 'DJ', 'iso_code3' => 'DJI', 'name' => 'Djibouti', 'is_others' => false],
			['id' => 60, 'iso_code' => 'DM', 'iso_code3' => 'DMA', 'name' => 'Dominica', 'is_others' => false],
			['id' => 61, 'iso_code' => 'DO', 'iso_code3' => 'DOM', 'name' => 'Dominican Republic', 'is_others' => false],
			['id' => 62, 'iso_code' => 'EC', 'iso_code3' => 'ECU', 'name' => 'Ecuador', 'is_others' => false],
			['id' => 63, 'iso_code' => 'EG', 'iso_code3' => 'EGY', 'name' => 'Egypt', 'is_others' => false],
			['id' => 64, 'iso_code' => 'SV', 'iso_code3' => 'SLV', 'name' => 'El Salvador', 'is_others' => false],
			['id' => 65, 'iso_code' => 'GQ', 'iso_code3' => 'GNQ', 'name' => 'Equatorial Guinea', 'is_others' => false],
			['id' => 66, 'iso_code' => 'ER', 'iso_code3' => 'ERI', 'name' => 'Eritrea', 'is_others' => false],
			['id' => 67, 'iso_code' => 'EE', 'iso_code3' => 'EST', 'name' => 'Estonia', 'is_others' => false],
			['id' => 68, 'iso_code' => 'ET', 'iso_code3' => 'ETH', 'name' => 'Ethiopia', 'is_others' => false],
			['id' => 69, 'iso_code' => 'FK', 'iso_code3' => 'FLK', 'name' => 'Falkland Islands (Malvinas)', 'is_others' => false],
			['id' => 70, 'iso_code' => 'FO', 'iso_code3' => 'FRO', 'name' => 'Faroe Islands', 'is_others' => false],
			['id' => 71, 'iso_code' => 'FJ', 'iso_code3' => 'FJI', 'name' => 'Fiji', 'is_others' => false],
			['id' => 72, 'iso_code' => 'FI', 'iso_code3' => 'FIN', 'name' => 'Finland', 'is_others' => false],
			['id' => 73, 'iso_code' => 'FR', 'iso_code3' => 'FRA', 'name' => 'France', 'is_others' => false],
			['id' => 74, 'iso_code' => 'GF', 'iso_code3' => 'GUF', 'name' => 'French Guiana', 'is_others' => false],
			['id' => 75, 'iso_code' => 'PF', 'iso_code3' => 'PYF', 'name' => 'French Polynesia', 'is_others' => false],
			['id' => 76, 'iso_code' => 'TF', 'iso_code3' => 'ATF', 'name' => 'French Southern Territories', 'is_others' => false],
			['id' => 77, 'iso_code' => 'GA', 'iso_code3' => 'GAB', 'name' => 'Gabon', 'is_others' => false],
			['id' => 78, 'iso_code' => 'GM', 'iso_code3' => 'GMB', 'name' => 'Gambia', 'is_others' => false],
			['id' => 79, 'iso_code' => 'GE', 'iso_code3' => 'GEO', 'name' => 'Georgia', 'is_others' => false],
			['id' => 80, 'iso_code' => 'DE', 'iso_code3' => 'DEU', 'name' => 'Germany', 'is_others' => false],
			['id' => 81, 'iso_code' => 'GH', 'iso_code3' => 'GHA', 'name' => 'Ghana', 'is_others' => false],
			['id' => 82, 'iso_code' => 'GI', 'iso_code3' => 'GIB', 'name' => 'Gibraltar', 'is_others' => false],
			['id' => 83, 'iso_code' => 'GR', 'iso_code3' => 'GRC', 'name' => 'Greece', 'is_others' => false],
			['id' => 84, 'iso_code' => 'GL', 'iso_code3' => 'GRL', 'name' => 'Greenland', 'is_others' => false],
			['id' => 85, 'iso_code' => 'GD', 'iso_code3' => 'GRD', 'name' => 'Grenada', 'is_others' => false],
			['id' => 86, 'iso_code' => 'GP', 'iso_code3' => 'GLP', 'name' => 'Guadeloupe', 'is_others' => false],
			['id' => 87, 'iso_code' => 'GU', 'iso_code3' => 'GUM', 'name' => 'Guam', 'is_others' => false],
			['id' => 88, 'iso_code' => 'GT', 'iso_code3' => 'GTM', 'name' => 'Guatemala', 'is_others' => false],
			['id' => 89, 'iso_code' => 'GN', 'iso_code3' => 'GIN', 'name' => 'Guinea', 'is_others' => false],
			['id' => 90, 'iso_code' => 'GW', 'iso_code3' => 'GNB', 'name' => 'Guinea-Bissau', 'is_others' => false],
			['id' => 91, 'iso_code' => 'GY', 'iso_code3' => 'GUY', 'name' => 'Guyana', 'is_others' => false],
			['id' => 92, 'iso_code' => 'HT', 'iso_code3' => 'HTI', 'name' => 'Haiti', 'is_others' => false],
			['id' => 93, 'iso_code' => 'HM', 'iso_code3' => 'HMD', 'name' => 'Heard Island and McDonald Islands', 'is_others' => false],
			['id' => 94, 'iso_code' => 'VA', 'iso_code3' => 'VAT', 'name' => 'Holy See (Vatican City State)', 'is_others' => false],
			['id' => 95, 'iso_code' => 'HN', 'iso_code3' => 'HND', 'name' => 'Honduras', 'is_others' => false],
			['id' => 96, 'iso_code' => 'HK', 'iso_code3' => 'HKG', 'name' => 'Hong Kong', 'is_others' => false],
			['id' => 97, 'iso_code' => 'HU', 'iso_code3' => 'HUN', 'name' => 'Hungary', 'is_others' => false],
			['id' => 98, 'iso_code' => 'IS', 'iso_code3' => 'ISL', 'name' => 'Iceland', 'is_others' => false],
			['id' => 99, 'iso_code' => 'IN', 'iso_code3' => 'IND', 'name' => 'India', 'is_others' => false],
			['id' => 100, 'iso_code' => 'ID', 'iso_code3' => 'IDN', 'name' => 'Indonesia', 'is_others' => false],
			['id' => 101, 'iso_code' => 'IR', 'iso_code3' => 'IRN', 'name' => 'Iran, Islamic Republic of', 'is_others' => false],
			['id' => 102, 'iso_code' => 'IQ', 'iso_code3' => 'IRQ', 'name' => 'Iraq', 'is_others' => false],
			['id' => 103, 'iso_code' => 'IE', 'iso_code3' => 'IRL', 'name' => 'Ireland', 'is_others' => false],
			['id' => 104, 'iso_code' => 'IL', 'iso_code3' => 'ISR', 'name' => 'Israel', 'is_others' => false],
			['id' => 105, 'iso_code' => 'IT', 'iso_code3' => 'ITA', 'name' => 'Italy', 'is_others' => false],
			['id' => 106, 'iso_code' => 'JM', 'iso_code3' => 'JAM', 'name' => 'Jamaica', 'is_others' => false],
			['id' => 107, 'iso_code' => 'JP', 'iso_code3' => 'JPN', 'name' => 'Japan', 'is_others' => false],
			['id' => 108, 'iso_code' => 'JO', 'iso_code3' => 'JOR', 'name' => 'Jordan', 'is_others' => false],
			['id' => 109, 'iso_code' => 'KZ', 'iso_code3' => 'KAZ', 'name' => 'Kazakhstan', 'is_others' => false],
			['id' => 110, 'iso_code' => 'KE', 'iso_code3' => 'KEN', 'name' => 'Kenya', 'is_others' => false],
			['id' => 111, 'iso_code' => 'KI', 'iso_code3' => 'KIR', 'name' => 'Kiribati', 'is_others' => false],
			['id' => 112, 'iso_code' => 'KP', 'iso_code3' => 'PRK', 'name' => 'Korea, Democratic People\'s Republic of', 'is_others' => false],
			['id' => 113, 'iso_code' => 'KR', 'iso_code3' => 'KOR', 'name' => 'Korea, Republic of', 'is_others' => false],
			['id' => 114, 'iso_code' => 'KW', 'iso_code3' => 'KWT', 'name' => 'Kuwait', 'is_others' => false],
			['id' => 115, 'iso_code' => 'KG', 'iso_code3' => 'KGZ', 'name' => 'Kyrgyzstan', 'is_others' => false],
			['id' => 116, 'iso_code' => 'LA', 'iso_code3' => 'LAO', 'name' => 'Lao People\'s Democratic Republic', 'is_others' => false],
			['id' => 117, 'iso_code' => 'LV', 'iso_code3' => 'LVA', 'name' => 'Latvia', 'is_others' => false],
			['id' => 118, 'iso_code' => 'LB', 'iso_code3' => 'LBN', 'name ' => 'Lebanon', 'is_others' => false],
			['id' => 119, 'iso_code' => 'LS', 'iso_code3' => 'LSO', 'name' => 'Lesotho', 'is_others' => false],
			['id' => 120, 'iso_code' => 'LR', 'iso_code3' => 'LBR', 'name' => 'Liberia', 'is_others' => false],
			['id' => 121, 'iso_code' => 'LY', 'iso_code3' => 'LBY', 'name' => 'Libyan Arab Jamahiriya', 'is_others' => false],
			['id' => 122, 'iso_code' => 'LI', 'iso_code3' => 'LIE', 'name' => 'Liechtenstein', 'is_others' => false],
			['id' => 123, 'iso_code' => 'LT', 'iso_code3' => 'LTU', 'name' => 'Lithuania', 'is_others' => false],
			['id' => 124, 'iso_code' => 'LU', 'iso_code3' => 'LUX', 'name' => 'Luxembourg', 'is_others' => false],
			['id' => 125, 'iso_code' => 'MO', 'iso_code3' => 'MAC', 'name' => 'Macao', 'is_others' => false],
			['id' => 126, 'iso_code' => 'MK', 'iso_code3' => 'MKD', 'name' => 'Macedonia, The Former Yugoslav Republic of', 'is_others' => false],
			['id' => 127, 'iso_code' => 'MG', 'iso_code3' => 'MDG', 'name' => 'Madagascar', 'is_others' => false],
			['id' => 128, 'iso_code' => 'MW', 'iso_code3' => 'MWI', 'name' => 'Malawi', 'is_others' => false],
			['id' => 129, 'iso_code' => 'MY', 'iso_code3' => 'MYS', 'name' => 'Malaysia', 'is_others' => false],
			['id' => 130, 'iso_code' => 'MV', 'iso_code3' => 'MDV', 'name' => 'Maldives', 'is_others' => false],
			['id' => 131, 'iso_code' => 'ML', 'iso_code3' => 'MLI', 'name' => 'Mali', 'is_others' => false],
			['id' => 132, 'iso_code' => 'MT', 'iso_code3' => 'MLT', 'name' => 'Malta', 'is_others' => false],
			['id' => 133, 'iso_code' => 'MH', 'iso_code3' => 'MHL', 'name' => 'Marshall Islands', 'is_others' => false],
			['id' => 134, 'iso_code' => 'MQ', 'iso_code3' => 'MTQ', 'name' => 'Martinique', 'is_others' => false],
			['id' => 135, 'iso_code' => 'MR', 'iso_code3' => 'MRT', 'name' => 'Mauritania', 'is_others' => false],
			['id' => 136, 'iso_code' => 'MU', 'iso_code3' => 'MUS', 'name' => 'Mauritius', 'is_others' => false],
			['id' => 137, 'iso_code' => 'YT', 'iso_code3' => 'MYT', 'name' => 'Mayotte', 'is_others' => false],
			['id' => 138, 'iso_code' => 'MX', 'iso_code3' => 'MEX', 'name' => 'Mexico', 'is_others' => false],
			['id' => 139, 'iso_code' => 'FM', 'iso_code3' => 'FSM', 'name' => 'Micronesia, Federated States of', 'is_others' => false],
			['id' => 140, 'iso_code' => 'MD', 'iso_code3' => 'MDA', 'name' => 'Moldova, Republic of', 'is_others' => false],
			['id' => 141, 'iso_code' => 'MC', 'iso_code3' => 'MCO', 'name' => 'Monaco', 'is_others' => false],
			['id' => 142, 'iso_code' => 'MN', 'iso_code3' => 'MNG', 'name' => 'Mongolia', 'is_others' => false],
			['id' => 143, 'iso_code' => 'MS', 'iso_code3' => 'MSR', 'name' => 'Montserrat', 'is_others' => false],
			['id' => 144, 'iso_code' => 'MA', 'iso_code3' => 'MAR', 'name' => 'Morocco', 'is_others' => false],
			['id' => 145, 'iso_code' => 'MZ', 'iso_code3' => 'MOZ', 'name' => 'Mozambique', 'is_others' => false],
			['id' => 146, 'iso_code' => 'MM', 'iso_code3' => 'MMR', 'name' => 'Myanmar', 'is_others' => false],
			['id' => 147, 'iso_code' => 'NA', 'iso_code3' => 'NAM', 'name' => 'Namibia', 'is_others' => false],
			['id' => 148, 'iso_code' => 'NR', 'iso_code3' => 'NRU', 'name' => 'Nauru', 'is_others' => false],
			['id' => 149, 'iso_code' => 'NP', 'iso_code3' => 'NPL', 'name' => 'Nepal', 'is_others' => false],
			['id' => 150, 'iso_code' => 'NL', 'iso_code3' => 'NLD', 'name' => 'Netherlands', 'is_others' => false],
			['id' => 151, 'iso_code' => 'AN', 'iso_code3' => 'ANT', 'name' => 'Netherlands Antilles', 'is_others' => false],
			['id' => 152, 'iso_code' => 'NC', 'iso_code3' => 'NCL', 'name' => 'New Caledonia', 'is_others' => false],
			['id' => 153, 'iso_code' => 'NZ', 'iso_code3' => 'NZL', 'name' => 'New Zealand', 'is_others' => false],
			['id' => 154, 'iso_code' => 'NI', 'iso_code3' => 'NIC', 'name' => 'Nicaragua', 'is_others' => false],
			['id' => 155, 'iso_code' => 'NE', 'iso_code3' => 'NER', 'name' => 'Niger', 'is_others' => false],
			['id' => 156, 'iso_code' => 'NG', 'iso_code3' => 'NGA', 'name' => 'Nigeria', 'is_others' => false],
			['id' => 157, 'iso_code' => 'NU', 'iso_code3' => 'NIU', 'name' => 'Niue', 'is_others' => false],
			['id' => 158, 'iso_code' => 'NF', 'iso_code3' => 'NFK', 'name' => 'Norfolk Island', 'is_others' => false],
			['id' => 159, 'iso_code' => 'MP', 'iso_code3' => 'MNP', 'name' => 'Northern Mariana Islands', 'is_others' => false],
			['id' => 160, 'iso_code' => 'NO', 'iso_code3 ' => 'NOR', 'name' => 'Norway', 'is_others' => false],
			['id' => 161, 'iso_code' => 'OM', 'iso_code3' => 'OMN', 'name' => 'Oman', 'is_others' => false],
			['id' => 162, 'iso_code' => 'PK', 'iso_code3' => 'PAK', 'name' => 'Pakistan', 'is_others' => false],
			['id' => 163, 'iso_code' => 'PW', 'iso_code3' => 'PLW', 'name' => 'Palau', 'is_others' => false],
			['id' => 164, 'iso_code' => 'PS', 'iso_code3' => 'PSE', 'name' => 'Palestinian Territory, Occupied', 'is_others' => false],
			['id' => 165, 'iso_code' => 'PA', 'iso_code3' => 'PAN', 'name' => 'Panama', 'is_others' => false],
			['id' => 166, 'iso_code' => 'PG', 'iso_code3' => 'PNG', 'name' => 'Papua New Guinea', 'is_others' => false],
			['id' => 167, 'iso_code' => 'PY', 'iso_code3' => 'PRY', 'name' => 'Paraguay', 'is_others' => false],
			['id' => 168, 'iso_code' => 'PE', 'iso_code3' => 'PER', 'name' => 'Peru', 'is_others' => false],
			['id' => 169, 'iso_code' => 'PH', 'iso_code3' => 'PHL', 'name' => 'Philippines', 'is_others' => false],
			['id' => 170, 'iso_code' => 'PN', 'iso_code3' => 'PCN', 'name' => 'Pitcairn', 'is_others' => false],
			['id' => 171, 'iso_code' => 'PL', 'iso_code3' => 'POL', 'name' => 'Poland', 'is_others' => false],
			['id' => 172, 'iso_code' => 'PT', 'iso_code3' => 'PRT', 'name' => 'Portugal', 'is_others' => false],
			['id' => 173, 'iso_code' => 'PR', 'iso_code3' => 'PRI', 'name' => 'Puerto Rico', 'is_others' => false],
			['id' => 174, 'iso_code' => 'QA', 'iso_code3' => 'QAT', 'name' => 'Qatar', 'is_others' => false],
			['id' => 175, 'iso_code' => 'RE', 'iso_code3' => 'REU', 'name' => 'Reunion', 'is_others' => false],
			['id' => 176, 'iso_code' => 'RO', 'iso_code3' => 'ROM', 'name' => 'Romania', 'is_others' => false],
			['id' => 177, 'iso_code' => 'RU', 'iso_code3' => 'RUS', 'name' => 'Russian Federation', 'is_others' => false],
			['id' => 178, 'iso_code' => 'RW', 'iso_code3' => 'RWA', 'name' => 'Rwanda', 'is_others' => false],
			['id' => 179, 'iso_code' => 'SH', 'iso_code3' => 'SHN', 'name' => 'Saint Helena', 'is_others' => false],
			['id' => 180, 'iso_code' => 'KN', 'iso_code3' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'is_others' => false],
			['id' => 181, 'iso_code' => 'LC', 'iso_code3' => 'LCA', 'name' => 'Saint Lucia', 'is_others' => false],
			['id' => 182, 'iso_code' => 'PM', 'iso_code3' => 'SPM', 'name' => 'Saint Pierre and Miquelon', 'is_others' => false],
			['id' => 183, 'iso_code' => 'VC', 'iso_code3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'is_others' => false],
			['id' => 184, 'iso_code' => 'WS', 'iso_code3' => 'WSM', 'name' => 'Samoa', 'is_others' => false],
			['id' => 185, 'iso_code' => 'SM', 'iso_code3' => 'SMR', 'name' => 'San Marino', 'is_others' => false],
			['id' => 186, 'iso_code' => 'ST', 'iso_code3' => 'STP', 'name' => 'Sao Tome and Principe', 'is_others' => false],
			['id' => 187, 'iso_code' => 'SA', 'iso_code3' => 'SAU', 'name' => 'Saudi Arabia', 'is_others' => false],
			['id' => 188, 'iso_code' => 'SN', 'iso_code3' => 'SEN', 'name' => 'Senegal', 'is_others' => false],
			['id' => 189, 'iso_code' => 'CS', 'iso_code3' => 'SCG', 'name' => 'Serbia and Montenegro', 'is_others' => false],
			['id' => 190, 'iso_code' => 'SC', 'iso_code3' => 'SYC', 'name' => 'Seychelles', 'is_others' => false],
			['id' => 191, 'iso_code' => 'SL', 'iso_code3' => 'SLE', 'name' => 'Sierra Leone', 'is_others' => false],
			['id' => 192, 'iso_code' => 'SG', 'iso_code3' => 'SGP', 'name' => 'Singapore', 'is_others' => false],
			['id' => 193, 'iso_code' => 'SK', 'iso_code3' => 'SVK', 'name' => 'Slovakia', 'is_others' => false],
			['id' => 194, 'iso_code' => 'SI', 'iso_code3' => 'SVN', 'name' => 'Slovenia', 'is_others' => false],
			['id' => 195, 'iso_code' => 'SB', 'iso_code3' => 'SLB', 'name' => 'Solomon Islands', 'is_others' => false],
			['id' => 196, 'iso_code' => 'SO', 'iso_code3' => 'SOM', 'name' => 'Somalia', 'is_others' => false],
			['id' => 197, 'iso_code' => 'ZA', 'iso_code3' => 'ZAF', 'name' => 'South Africa', 'is_others' => false],
			['id' => 198, 'iso_code' => 'GS', 'iso_code3' => 'SGS', 'name' => 'South Georgia and the South Sandwich Islands', 'is_others' => false],
			['id' => 199, 'iso_code' => 'ES', 'iso_code3' => 'ESP', 'name' => 'Spain', 'is_others' => false],
			['id' => 200, 'iso_code' => 'LK', 'iso_code3' => 'LKA', 'name' => 'Sri Lanka', 'is_others' => false],
			['id' => 201, 'iso_code' => 'SD', 'iso_code3' => 'SDN', 'name' => 'Sudan', 'is_others' => false],
			['id' => 202, 'iso_code' => 'SR', 'iso_code3' => 'SUR', 'name' => 'Suriname', 'is_others' => false],
			['id' => 203, 'iso_code' => 'SJ', 'iso_code3' => 'SJM', 'name' => 'Svalbard and Jan Mayen', 'is_others' => false],
			['id' => 204, 'iso_code' => 'SZ', 'iso_code3' => 'SWZ', 'name' => 'Swaziland', 'is_others' => false],
			['id' => 205, 'iso_code' => 'SE', 'iso_code3' => 'SWE', 'name' => 'Sweden', 'is_others' => false],
			['id' => 206, 'iso_code' => 'CH', 'iso_code3' => 'CHE', 'name' => 'Switzerland', 'is_others' => false],
			['id' => 207, 'iso_code' => 'SY', 'iso_code3' => 'SYR', 'name' => 'Syrian Arab Republic', 'is_others' => false],
			['id' => 208, 'iso_code' => 'TW', 'iso_code3' => 'TWN', 'name' => 'Taiwan', 'is_others' => false],
			['id' => 209, 'iso_code' => 'TJ', 'iso_code3' => 'TJK', 'name' => 'Tajikistan', 'is_others' => false],
			['id' => 210, 'iso_code' => 'TZ', 'iso_code3' => 'TZA', 'name' => 'Tanzania, United Republic of', 'is_others' => false],
			['id' => 211, 'iso_code' => 'TH', 'iso_code3' => 'THA', 'name' => 'Thailand', 'is_others' => false],
			['id' => 212, 'iso_code' => 'TL', 'iso_code3' => 'TLS', 'name' => 'Timor-Leste', 'is_others' => false],
			['id' => 213, 'iso_code' => 'TG', 'iso_code3' => 'TGO', 'name' => 'Togo', 'is_others' => false],
			['id' => 214, 'iso_code' => 'TK', 'iso_code3' => 'TKL', 'name' => 'Tokelau', 'is_others' => false],
			['id' => 215, 'iso_code' => 'TO', 'iso_code3' => 'TON', 'name' => 'Tonga', 'is_others' => false],
			['id' => 216, 'iso_code' => 'TT', 'iso_code3' => 'TTO', 'name' => 'Trinidad and Tobago', 'is_others' => false],
			['id' => 217, 'iso_code' => 'TN', 'iso_code3' => 'TUN', 'name' => 'Tunisia', 'is_others' => false],
			['id' => 218, 'iso_code' => 'TR', 'iso_code3' => 'TUR', 'name' => 'Turkey', 'is_others' => false],
			['id' => 219, 'iso_code' => 'TM', 'iso_code3' => 'TKM', 'name' => 'Turkmenistan', 'is_others' => false],
			['id' => 220, 'iso_code' => 'TC', 'iso_code3' => 'TCA', 'name' => 'Turks and Caicos Islands', 'is_others' => false],
			['id' => 221, 'iso_code' => 'TV', 'iso_code3' => 'TUV', 'name' => 'Tuvalu', 'is_others' => false],
			['id' => 222, 'iso_code' => 'UG', 'iso_code3' => 'UGA', 'name' => 'Uganda', 'is_others' => false],
			['id' => 223, 'iso_code' => 'UA', 'iso_code3' => 'UKR', 'name' => 'Ukraine', 'is_others' => false],
			['id' => 224, 'iso_code' => 'AE', 'iso_code3' => 'ARE', 'name' => 'United Arab Emirates', 'is_others' => false],
			['id' => 225, 'iso_code' => 'GB', 'iso_code3' => 'GBR', 'name' => 'United Kingdom', 'is_others' => false],
			['id' => 226, 'iso_code' => 'US', 'iso_code3' => 'USA', 'name' => 'United States', 'is_others' => false],
			['id' => 227, 'iso_code' => 'UM', 'iso_code3' => 'UMI', 'name' => 'United States Minor Outlying Islands', 'is_others' => false],
			['id' => 228, 'iso_code' => 'UY', 'iso_code3' => 'URY', 'name' => 'Uruguay', 'is_others' => false],
			['id' => 229, 'iso_code' => 'UZ', 'iso_code3' => 'UZB', 'name' => 'Uzbekistan', 'is_others' => false],
			['id' => 230, 'iso_code' => 'VU', 'iso_code3' => 'VUT', 'name' => 'Vanuatu', 'is_others' => false],
			['id' => 231, 'iso_code' => 'VE', 'iso_code3' => 'VEN', 'name' => 'Venezuela', 'is_others' => false],
			['id' => 232, 'iso_code' => 'VN', 'iso_code3' => 'VNM', 'name' => 'Viet Nam', 'is_others' => false],
			['id' => 233, 'iso_code' => 'VG', 'iso_code3' => 'VGB', 'name' => 'Virgin Islands, British', 'is_others' => false],
			['id' => 234, 'iso_code' => 'VI', 'iso_code3' => 'VIR', 'name' => 'Virgin Islands, U.S.', 'is_others' => false],
			['id' => 235, 'iso_code' => 'WF', 'iso_code3' => 'WLF', 'name' => 'Wallis and Futuna', 'is_others' => false],
			['id' => 236, 'iso_code' => 'EH', 'iso_code3' => 'ESH', 'name' => 'Western Sahara', 'is_others' => false],
			['id' => 237, 'iso_code' => 'YE', 'iso_code3' => 'YEM', 'name' => 'Yemen', 'is_others' => false],
			['id' => 238, 'iso_code' => 'ZM', 'iso_code3' => 'ZMB', 'name' => 'Zambia', 'is_others' => false],
			['id' => 239, 'iso_code' => 'ZW', 'iso_code3' => 'ZWE', 'name' => 'Zimbabwe', 'is_others' => false],
			['id' => 240, 'iso_code' => '--', 'iso_code3' => '---', 'name' => 'Others', 'is_others' => true],
		]);
	}

	public function down(): void
	{
		$pdo = $this->databaseProvider->getDatabase()->getPdo();

		$pdo->exec('TRUNCATE `countries`;');
		$pdo->exec('TRUNCATE `groups`;');
		$pdo->exec('TRUNCATE `tickers`;');
		$pdo->exec('TRUNCATE `brokers`;');
		$pdo->exec('TRUNCATE `markets`;');
		$pdo->exec('TRUNCATE `users`;');
		$pdo->exec('TRUNCATE `currencies`;');
	}
}
