<?php

declare(strict_types=1);

namespace Migration;

use Cycle\Migrations\Migration;

class TickerRelationsMigration extends Migration
{
	protected const DATABASE = 'default';

	public function up(): void
	{
		$this->table('countries')
			->addColumn('id', 'primary', [
				'nullable' => false,
				'defaultValue' => null,
				'size' => 11,
				'autoIncrement' => true,
				'unsigned' => false,
				'zerofill' => false,
			])
			->addColumn('iso_code', 'string', ['nullable' => false, 'defaultValue' => null, 'size' => 2])
			->addColumn('iso_code3', 'string', ['nullable' => false, 'defaultValue' => null, 'size' => 3])
			->addColumn('name', 'string', ['nullable' => false, 'defaultValue' => null, 'size' => 50])
			->setPrimaryKeys(['id'])
			->addIndex(['iso_code'], ['name' => 'countries_index_iso_code', 'unique' => true])
			->addIndex(['iso_code3'], ['name' => 'countries_index_iso_code3', 'unique' => true])
			->addIndex(['name'], ['name' => 'countries_index_name', 'unique' => true])
			->create();

		$this->database()->insert('countries')->values([
			['id' => 1, 'iso_code' => 'AF', 'iso_code3' => 'AFG', 'name' => 'Afghanistan'],
			['id' => 2, 'iso_code' => 'AL', 'iso_code3' => 'ALB', 'name' => 'Albania'],
			['id' => 3, 'iso_code' => 'DZ', 'iso_code3' => 'DZA', 'name' => 'Algeria'],
			['id' => 4, 'iso_code' => 'AS', 'iso_code3' => 'ASM', 'name' => 'American Samoa'],
			['id' => 5, 'iso_code' => 'AD', 'iso_code3' => 'AND', 'name' => 'Andorra'],
			['id' => 6, 'iso_code' => 'AO', 'iso_code3' => 'AGO', 'name' => 'Angola'],
			['id' => 7, 'iso_code' => 'AI', 'iso_code3' => 'AIA', 'name' => 'Anguilla'],
			['id' => 8, 'iso_code' => 'AQ', 'iso_code3' => 'ATA', 'name' => 'Antarctica'],
			['id' => 9, 'iso_code' => 'AG', 'iso_code3' => 'ATG', 'name' => 'Antigua and Barbuda'],
			['id' => 10, 'iso_code' => 'AR', 'iso_code3' => 'ARG', 'name' => 'Argentina'],
			['id' => 11, 'iso_code' => 'AM', 'iso_code3' => 'ARM', 'name' => 'Armenia'],
			['id' => 12, 'iso_code' => 'AW', 'iso_code3' => 'ABW', 'name' => 'Aruba'],
			['id' => 13, 'iso_code' => 'AU', 'iso_code3' => 'AUS', 'name' => 'Australia'],
			['id' => 14, 'iso_code' => 'AT', 'iso_code3' => 'AUT', 'name' => 'Austria'],
			['id' => 15, 'iso_code' => 'AZ', 'iso_code3' => 'AZE', 'name' => 'Azerbaijan'],
			['id' => 16, 'iso_code' => 'BS', 'iso_code3' => 'BHS', 'name' => 'Bahamas'],
			['id' => 17, 'iso_code' => 'BH', 'iso_code3' => 'BHR', 'name' => 'Bahrain'],
			['id' => 18, 'iso_code' => 'BD', 'iso_code3' => 'BGD', 'name' => 'Bangladesh'],
			['id' => 19, 'iso_code' => 'BB', 'iso_code3' => 'BRB', 'name' => 'Barbados'],
			['id' => 20, 'iso_code' => 'BY', 'iso_code3' => 'BLR', 'name' => 'Belarus'],
			['id' => 21, 'iso_code' => 'BE', 'iso_code3' => 'BEL', 'name' => 'Belgium'],
			['id' => 22, 'iso_code' => 'BZ', 'iso_code3' => 'BLZ', 'name' => 'Belize'],
			['id' => 23, 'iso_code' => 'BJ', 'iso_code3' => 'BEN', 'name' => 'Benin'],
			['id' => 24, 'iso_code' => 'BM', 'iso_code3' => 'BMU', 'name' => 'Bermuda'],
			['id' => 25, 'iso_code' => 'BT', 'iso_code3' => 'BTN', 'name' => 'Bhutan'],
			['id' => 26, 'iso_code' => 'BO', 'iso_code3' => 'BOL', 'name' => 'Bolivia'],
			['id' => 27, 'iso_code' => 'BA', 'iso_code3' => 'BIH', 'name' => 'Bosnia and Herzegovina'],
			['id' => 28, 'iso_code' => 'BW', 'iso_code3' => 'BWA', 'name' => 'Botswana'],
			['id' => 29, 'iso_code' => 'BV', 'iso_code3' => 'BVT', 'name' => 'Bouvet Island'],
			['id' => 30, 'iso_code' => 'BR', 'iso_code3' => 'BRA', 'name' => 'Brazil'],
			['id' => 31, 'iso_code' => 'IO', 'iso_code3' => 'IOT', 'name' => 'British Indian Ocean Territory'],
			['id' => 32, 'iso_code' => 'BN', 'iso_code3' => 'BRN', 'name' => 'Brunei Darussalam'],
			['id' => 33, 'iso_code' => 'BG', 'iso_code3' => 'BGR', 'name' => 'Bulgaria'],
			['id' => 34, 'iso_code' => 'BF', 'iso_code3' => 'BFA', 'name' => 'Burkina Faso'],
			['id' => 35, 'iso_code' => 'BI', 'iso_code3' => 'BDI', 'name' => 'Burundi'],
			['id' => 36, 'iso_code' => 'KH', 'iso_code3' => 'KHM', 'name' => 'Cambodia'],
			['id' => 37, 'iso_code' => 'CM', 'iso_code3' => 'CMR', 'name' => 'Cameroon'],
			['id' => 38, 'iso_code' => 'CA', 'iso_code3' => 'CAN', 'name' => 'Canada'],
			['id' => 39, 'iso_code' => 'CV', 'iso_code3' => 'CPV', 'name' => 'Cape Verde'],
			['id' => 40, 'iso_code' => 'KY', 'iso_code3' => 'CYM', 'name' => 'Cayman Islands'],
			['id' => 41, 'iso_code' => 'CF', 'iso_code3' => 'CAF', 'name' => 'Central African Republic'],
			['id' => 42, 'iso_code' => 'TD', 'iso_code3' => 'TCD', 'name' => 'Chad'],
			['id' => 43, 'iso_code' => 'CL', 'iso_code3' => 'CHL', 'name' => 'Chile'],
			['id' => 44, 'iso_code' => 'CN', 'iso_code3' => 'CHN', 'name' => 'China'],
			['id' => 45, 'iso_code' => 'CX', 'iso_code3' => 'CXR', 'name' => 'Christmas Island'],
			['id' => 46, 'iso_code' => 'CC', 'iso_code3' => 'CCK', 'name' => 'Cocos (Keeling) Islands'],
			['id' => 47, 'iso_code' => 'CO', 'iso_code3' => 'COL', 'name' => 'Colombia'],
			['id' => 48, 'iso_code' => 'KM', 'iso_code3' => 'COM', 'name' => 'Comoros'],
			['id' => 49, 'iso_code' => 'CG', 'iso_code3' => 'COG', 'name' => 'Congo'],
			['id' => 50, 'iso_code' => 'CD', 'iso_code3' => 'COD', 'name' => 'Congo, The Democratic Republic of the'],
			['id' => 51, 'iso_code' => 'CK', 'iso_code3' => 'COK', 'name' => 'Cook Islands'],
			['id' => 52, 'iso_code' => 'CR', 'iso_code3' => 'CRI', 'name' => 'Costa Rica'],
			['id' => 53, 'iso_code' => 'CI', 'iso_code3' => 'CIV', 'name' => 'Cote d\'Ivoire'],
			['id' => 54, 'iso_code' => 'HR', 'iso_code3' => 'HRV', 'name' => 'Croatia'],
			['id' => 55, 'iso_code' => 'CU', 'iso_code3' => 'CUB', 'name' => 'Cuba'],
			['id' => 56, 'iso_code' => 'CY', 'iso_code3' => 'CYP', 'name' => 'Cyprus'],
			['id' => 57, 'iso_code' => 'CZ', 'iso_code3' => 'CZE', 'name' => 'Czech Republic'],
			['id' => 58, 'iso_code' => 'DK', 'iso_code3' => 'DNK', 'name' => 'Denmark'],
			['id' => 59, 'iso_code' => 'DJ', 'iso_code3' => 'DJI', 'name' => 'Djibouti'],
			['id' => 60, 'iso_code' => 'DM', 'iso_code3' => 'DMA', 'name' => 'Dominica'],
			['id' => 61, 'iso_code' => 'DO', 'iso_code3' => 'DOM', 'name' => 'Dominican Republic'],
			['id' => 62, 'iso_code' => 'EC', 'iso_code3' => 'ECU', 'name' => 'Ecuador'],
			['id' => 63, 'iso_code' => 'EG', 'iso_code3' => 'EGY', 'name' => 'Egypt'],
			['id' => 64, 'iso_code' => 'SV', 'iso_code3' => 'SLV', 'name' => 'El Salvador'],
			['id' => 65, 'iso_code' => 'GQ', 'iso_code3' => 'GNQ', 'name' => 'Equatorial Guinea'],
			['id' => 66, 'iso_code' => 'ER', 'iso_code3' => 'ERI', 'name' => 'Eritrea'],
			['id' => 67, 'iso_code' => 'EE', 'iso_code3' => 'EST', 'name' => 'Estonia'],
			['id' => 68, 'iso_code' => 'ET', 'iso_code3' => 'ETH', 'name' => 'Ethiopia'],
			['id' => 69, 'iso_code' => 'FK', 'iso_code3' => 'FLK', 'name' => 'Falkland Islands (Malvinas)'],
			['id' => 70, 'iso_code' => 'FO', 'iso_code3' => 'FRO', 'name' => 'Faroe Islands'],
			['id' => 71, 'iso_code' => 'FJ', 'iso_code3' => 'FJI', 'name' => 'Fiji'],
			['id' => 72, 'iso_code' => 'FI', 'iso_code3' => 'FIN', 'name' => 'Finland'],
			['id' => 73, 'iso_code' => 'FR', 'iso_code3' => 'FRA', 'name' => 'France'],
			['id' => 74, 'iso_code' => 'GF', 'iso_code3' => 'GUF', 'name' => 'French Guiana'],
			['id' => 75, 'iso_code' => 'PF', 'iso_code3' => 'PYF', 'name' => 'French Polynesia'],
			['id' => 76, 'iso_code' => 'TF', 'iso_code3' => 'ATF', 'name' => 'French Southern Territories'],
			['id' => 77, 'iso_code' => 'GA', 'iso_code3' => 'GAB', 'name' => 'Gabon'],
			['id' => 78, 'iso_code' => 'GM', 'iso_code3' => 'GMB', 'name' => 'Gambia'],
			['id' => 79, 'iso_code' => 'GE', 'iso_code3' => 'GEO', 'name' => 'Georgia'],
			['id' => 80, 'iso_code' => 'DE', 'iso_code3' => 'DEU', 'name' => 'Germany'],
			['id' => 81, 'iso_code' => 'GH', 'iso_code3' => 'GHA', 'name' => 'Ghana'],
			['id' => 82, 'iso_code' => 'GI', 'iso_code3' => 'GIB', 'name' => 'Gibraltar'],
			['id' => 83, 'iso_code' => 'GR', 'iso_code3' => 'GRC', 'name' => 'Greece'],
			['id' => 84, 'iso_code' => 'GL', 'iso_code3' => 'GRL', 'name' => 'Greenland'],
			['id' => 85, 'iso_code' => 'GD', 'iso_code3' => 'GRD', 'name' => 'Grenada'],
			['id' => 86, 'iso_code' => 'GP', 'iso_code3' => 'GLP', 'name' => 'Guadeloupe'],
			['id' => 87, 'iso_code' => 'GU', 'iso_code3' => 'GUM', 'name' => 'Guam'],
			['id' => 88, 'iso_code' => 'GT', 'iso_code3' => 'GTM', 'name' => 'Guatemala'],
			['id' => 89, 'iso_code' => 'GN', 'iso_code3' => 'GIN', 'name' => 'Guinea'],
			['id' => 90, 'iso_code' => 'GW', 'iso_code3' => 'GNB', 'name' => 'Guinea-Bissau'],
			['id' => 91, 'iso_code' => 'GY', 'iso_code3' => 'GUY', 'name' => 'Guyana'],
			['id' => 92, 'iso_code' => 'HT', 'iso_code3' => 'HTI', 'name' => 'Haiti'],
			['id' => 93, 'iso_code' => 'HM', 'iso_code3' => 'HMD', 'name' => 'Heard Island and McDonald Islands'],
			['id' => 94, 'iso_code' => 'VA', 'iso_code3' => 'VAT', 'name' => 'Holy See (Vatican City State)'],
			['id' => 95, 'iso_code' => 'HN', 'iso_code3' => 'HND', 'name' => 'Honduras'],
			['id' => 96, 'iso_code' => 'HK', 'iso_code3' => 'HKG', 'name' => 'Hong Kong'],
			['id' => 97, 'iso_code' => 'HU', 'iso_code3' => 'HUN', 'name' => 'Hungary'],
			['id' => 98, 'iso_code' => 'IS', 'iso_code3' => 'ISL', 'name' => 'Iceland'],
			['id' => 99, 'iso_code' => 'IN', 'iso_code3' => 'IND', 'name' => 'India'],
			['id' => 100, 'iso_code' => 'ID', 'iso_code3' => 'IDN', 'name' => 'Indonesia'],
			['id' => 101, 'iso_code' => 'IR', 'iso_code3' => 'IRN', 'name' => 'Iran, Islamic Republic of'],
			['id' => 102, 'iso_code' => 'IQ', 'iso_code3' => 'IRQ', 'name' => 'Iraq'],
			['id' => 103, 'iso_code' => 'IE', 'iso_code3' => 'IRL', 'name' => 'Ireland'],
			['id' => 104, 'iso_code' => 'IL', 'iso_code3' => 'ISR', 'name' => 'Israel'],
			['id' => 105, 'iso_code' => 'IT', 'iso_code3' => 'ITA', 'name' => 'Italy'],
			['id' => 106, 'iso_code' => 'JM', 'iso_code3' => 'JAM', 'name' => 'Jamaica'],
			['id' => 107, 'iso_code' => 'JP', 'iso_code3' => 'JPN', 'name' => 'Japan'],
			['id' => 108, 'iso_code' => 'JO', 'iso_code3' => 'JOR', 'name' => 'Jordan'],
			['id' => 109, 'iso_code' => 'KZ', 'iso_code3' => 'KAZ', 'name' => 'Kazakhstan'],
			['id' => 110, 'iso_code' => 'KE', 'iso_code3' => 'KEN', 'name' => 'Kenya'],
			['id' => 111, 'iso_code' => 'KI', 'iso_code3' => 'KIR', 'name' => 'Kiribati'],
			['id' => 112, 'iso_code' => 'KP', 'iso_code3' => 'PRK', 'name' => 'Korea, Democratic People\'s Republic of'],
			['id' => 113, 'iso_code' => 'KR', 'iso_code3' => 'KOR', 'name' => 'Korea, Republic of'],
			['id' => 114, 'iso_code' => 'KW', 'iso_code3' => 'KWT', 'name' => 'Kuwait'],
			['id' => 115, 'iso_code' => 'KG', 'iso_code3' => 'KGZ', 'name' => 'Kyrgyzstan'],
			['id' => 116, 'iso_code' => 'LA', 'iso_code3' => 'LAO', 'name' => 'Lao People\'s Democratic Republic'],
			['id' => 117, 'iso_code' => 'LV', 'iso_code3' => 'LVA', 'name' => 'Latvia'],
			['id' => 118, 'iso_code' => 'LB', 'iso_code3' => 'LBN', 'name ' => 'Lebanon'],
			['id' => 119, 'iso_code' => 'LS', 'iso_code3' => 'LSO', 'name' => 'Lesotho'],
			['id' => 120, 'iso_code' => 'LR', 'iso_code3' => 'LBR', 'name' => 'Liberia'],
			['id' => 121, 'iso_code' => 'LY', 'iso_code3' => 'LBY', 'name' => 'Libyan Arab Jamahiriya'],
			['id' => 122, 'iso_code' => 'LI', 'iso_code3' => 'LIE', 'name' => 'Liechtenstein'],
			['id' => 123, 'iso_code' => 'LT', 'iso_code3' => 'LTU', 'name' => 'Lithuania'],
			['id' => 124, 'iso_code' => 'LU', 'iso_code3' => 'LUX', 'name' => 'Luxembourg'],
			['id' => 125, 'iso_code' => 'MO', 'iso_code3' => 'MAC', 'name' => 'Macao'],
			['id' => 126, 'iso_code' => 'MK', 'iso_code3' => 'MKD', 'name' => 'Macedonia, The Former Yugoslav Republic of'],
			['id' => 127, 'iso_code' => 'MG', 'iso_code3' => 'MDG', 'name' => 'Madagascar'],
			['id' => 128, 'iso_code' => 'MW', 'iso_code3' => 'MWI', 'name' => 'Malawi'],
			['id' => 129, 'iso_code' => 'MY', 'iso_code3' => 'MYS', 'name' => 'Malaysia'],
			['id' => 130, 'iso_code' => 'MV', 'iso_code3' => 'MDV', 'name' => 'Maldives'],
			['id' => 131, 'iso_code' => 'ML', 'iso_code3' => 'MLI', 'name' => 'Mali'],
			['id' => 132, 'iso_code' => 'MT', 'iso_code3' => 'MLT', 'name' => 'Malta'],
			['id' => 133, 'iso_code' => 'MH', 'iso_code3' => 'MHL', 'name' => 'Marshall Islands'],
			['id' => 134, 'iso_code' => 'MQ', 'iso_code3' => 'MTQ', 'name' => 'Martinique'],
			['id' => 135, 'iso_code' => 'MR', 'iso_code3' => 'MRT', 'name' => 'Mauritania'],
			['id' => 136, 'iso_code' => 'MU', 'iso_code3' => 'MUS', 'name' => 'Mauritius'],
			['id' => 137, 'iso_code' => 'YT', 'iso_code3' => 'MYT', 'name' => 'Mayotte'],
			['id' => 138, 'iso_code' => 'MX', 'iso_code3' => 'MEX', 'name' => 'Mexico'],
			['id' => 139, 'iso_code' => 'FM', 'iso_code3' => 'FSM', 'name' => 'Micronesia, Federated States of'],
			['id' => 140, 'iso_code' => 'MD', 'iso_code3' => 'MDA', 'name' => 'Moldova, Republic of'],
			['id' => 141, 'iso_code' => 'MC', 'iso_code3' => 'MCO', 'name' => 'Monaco'],
			['id' => 142, 'iso_code' => 'MN', 'iso_code3' => 'MNG', 'name' => 'Mongolia'],
			['id' => 143, 'iso_code' => 'MS', 'iso_code3' => 'MSR', 'name' => 'Montserrat'],
			['id' => 144, 'iso_code' => 'MA', 'iso_code3' => 'MAR', 'name' => 'Morocco'],
			['id' => 145, 'iso_code' => 'MZ', 'iso_code3' => 'MOZ', 'name' => 'Mozambique'],
			['id' => 146, 'iso_code' => 'MM', 'iso_code3' => 'MMR', 'name' => 'Myanmar'],
			['id' => 147, 'iso_code' => 'NA', 'iso_code3' => 'NAM', 'name' => 'Namibia'],
			['id' => 148, 'iso_code' => 'NR', 'iso_code3' => 'NRU', 'name' => 'Nauru'],
			['id' => 149, 'iso_code' => 'NP', 'iso_code3' => 'NPL', 'name' => 'Nepal'],
			['id' => 150, 'iso_code' => 'NL', 'iso_code3' => 'NLD', 'name' => 'Netherlands'],
			['id' => 151, 'iso_code' => 'AN', 'iso_code3' => 'ANT', 'name' => 'Netherlands Antilles'],
			['id' => 152, 'iso_code' => 'NC', 'iso_code3' => 'NCL', 'name' => 'New Caledonia'],
			['id' => 153, 'iso_code' => 'NZ', 'iso_code3' => 'NZL', 'name' => 'New Zealand'],
			['id' => 154, 'iso_code' => 'NI', 'iso_code3' => 'NIC', 'name' => 'Nicaragua'],
			['id' => 155, 'iso_code' => 'NE', 'iso_code3' => 'NER', 'name' => 'Niger'],
			['id' => 156, 'iso_code' => 'NG', 'iso_code3' => 'NGA', 'name' => 'Nigeria'],
			['id' => 157, 'iso_code' => 'NU', 'iso_code3' => 'NIU', 'name' => 'Niue'],
			['id' => 158, 'iso_code' => 'NF', 'iso_code3' => 'NFK', 'name' => 'Norfolk Island'],
			['id' => 159, 'iso_code' => 'MP', 'iso_code3' => 'MNP', 'name' => 'Northern Mariana Islands'],
			['id' => 160, 'iso_code' => 'NO', 'iso_code3 ' => 'NOR', 'name' => 'Norway'],
			['id' => 161, 'iso_code' => 'OM', 'iso_code3' => 'OMN', 'name' => 'Oman'],
			['id' => 162, 'iso_code' => 'PK', 'iso_code3' => 'PAK', 'name' => 'Pakistan'],
			['id' => 163, 'iso_code' => 'PW', 'iso_code3' => 'PLW', 'name' => 'Palau'],
			['id' => 164, 'iso_code' => 'PS', 'iso_code3' => 'PSE', 'name' => 'Palestinian Territory, Occupied'],
			['id' => 165, 'iso_code' => 'PA', 'iso_code3' => 'PAN', 'name' => 'Panama'],
			['id' => 166, 'iso_code' => 'PG', 'iso_code3' => 'PNG', 'name' => 'Papua New Guinea'],
			['id' => 167, 'iso_code' => 'PY', 'iso_code3' => 'PRY', 'name' => 'Paraguay'],
			['id' => 168, 'iso_code' => 'PE', 'iso_code3' => 'PER', 'name' => 'Peru'],
			['id' => 169, 'iso_code' => 'PH', 'iso_code3' => 'PHL', 'name' => 'Philippines'],
			['id' => 170, 'iso_code' => 'PN', 'iso_code3' => 'PCN', 'name' => 'Pitcairn'],
			['id' => 171, 'iso_code' => 'PL', 'iso_code3' => 'POL', 'name' => 'Poland'],
			['id' => 172, 'iso_code' => 'PT', 'iso_code3' => 'PRT', 'name' => 'Portugal'],
			['id' => 173, 'iso_code' => 'PR', 'iso_code3' => 'PRI', 'name' => 'Puerto Rico'],
			['id' => 174, 'iso_code' => 'QA', 'iso_code3' => 'QAT', 'name' => 'Qatar'],
			['id' => 175, 'iso_code' => 'RE', 'iso_code3' => 'REU', 'name' => 'Reunion'],
			['id' => 176, 'iso_code' => 'RO', 'iso_code3' => 'ROM', 'name' => 'Romania'],
			['id' => 177, 'iso_code' => 'RU', 'iso_code3' => 'RUS', 'name' => 'Russian Federation'],
			['id' => 178, 'iso_code' => 'RW', 'iso_code3' => 'RWA', 'name' => 'Rwanda'],
			['id' => 179, 'iso_code' => 'SH', 'iso_code3' => 'SHN', 'name' => 'Saint Helena'],
			['id' => 180, 'iso_code' => 'KN', 'iso_code3' => 'KNA', 'name' => 'Saint Kitts and Nevis'],
			['id' => 181, 'iso_code' => 'LC', 'iso_code3' => 'LCA', 'name' => 'Saint Lucia'],
			['id' => 182, 'iso_code' => 'PM', 'iso_code3' => 'SPM', 'name' => 'Saint Pierre and Miquelon'],
			['id' => 183, 'iso_code' => 'VC', 'iso_code3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines'],
			['id' => 184, 'iso_code' => 'WS', 'iso_code3' => 'WSM', 'name' => 'Samoa'],
			['id' => 185, 'iso_code' => 'SM', 'iso_code3' => 'SMR', 'name' => 'San Marino'],
			['id' => 186, 'iso_code' => 'ST', 'iso_code3' => 'STP', 'name' => 'Sao Tome and Principe'],
			['id' => 187, 'iso_code' => 'SA', 'iso_code3' => 'SAU', 'name' => 'Saudi Arabia'],
			['id' => 188, 'iso_code' => 'SN', 'iso_code3' => 'SEN', 'name' => 'Senegal'],
			['id' => 189, 'iso_code' => 'CS', 'iso_code3' => 'SCG', 'name' => 'Serbia and Montenegro'],
			['id' => 190, 'iso_code' => 'SC', 'iso_code3' => 'SYC', 'name' => 'Seychelles'],
			['id' => 191, 'iso_code' => 'SL', 'iso_code3' => 'SLE', 'name' => 'Sierra Leone'],
			['id' => 192, 'iso_code' => 'SG', 'iso_code3' => 'SGP', 'name' => 'Singapore'],
			['id' => 193, 'iso_code' => 'SK', 'iso_code3' => 'SVK', 'name' => 'Slovakia'],
			['id' => 194, 'iso_code' => 'SI', 'iso_code3' => 'SVN', 'name' => 'Slovenia'],
			['id' => 195, 'iso_code' => 'SB', 'iso_code3' => 'SLB', 'name' => 'Solomon Islands'],
			['id' => 196, 'iso_code' => 'SO', 'iso_code3' => 'SOM', 'name' => 'Somalia'],
			['id' => 197, 'iso_code' => 'ZA', 'iso_code3' => 'ZAF', 'name' => 'South Africa'],
			['id' => 198, 'iso_code' => 'GS', 'iso_code3' => 'SGS', 'name' => 'South Georgia and the South Sandwich Islands'],
			['id' => 199, 'iso_code' => 'ES', 'iso_code3' => 'ESP', 'name' => 'Spain'],
			['id' => 200, 'iso_code' => 'LK', 'iso_code3' => 'LKA', 'name' => 'Sri Lanka'],
			['id' => 201, 'iso_code' => 'SD', 'iso_code3' => 'SDN', 'name' => 'Sudan'],
			['id' => 202, 'iso_code' => 'SR', 'iso_code3' => 'SUR', 'name' => 'Suriname'],
			['id' => 203, 'iso_code' => 'SJ', 'iso_code3' => 'SJM', 'name' => 'Svalbard and Jan Mayen'],
			['id' => 204, 'iso_code' => 'SZ', 'iso_code3' => 'SWZ', 'name' => 'Swaziland'],
			['id' => 205, 'iso_code' => 'SE', 'iso_code3' => 'SWE', 'name' => 'Sweden'],
			['id' => 206, 'iso_code' => 'CH', 'iso_code3' => 'CHE', 'name' => 'Switzerland'],
			['id' => 207, 'iso_code' => 'SY', 'iso_code3' => 'SYR', 'name' => 'Syrian Arab Republic'],
			['id' => 208, 'iso_code' => 'TW', 'iso_code3' => 'TWN', 'name' => 'Taiwan'],
			['id' => 209, 'iso_code' => 'TJ', 'iso_code3' => 'TJK', 'name' => 'Tajikistan'],
			['id' => 210, 'iso_code' => 'TZ', 'iso_code3' => 'TZA', 'name' => 'Tanzania, United Republic of'],
			['id' => 211, 'iso_code' => 'TH', 'iso_code3' => 'THA', 'name' => 'Thailand'],
			['id' => 212, 'iso_code' => 'TL', 'iso_code3' => 'TLS', 'name' => 'Timor-Leste'],
			['id' => 213, 'iso_code' => 'TG', 'iso_code3' => 'TGO', 'name' => 'Togo'],
			['id' => 214, 'iso_code' => 'TK', 'iso_code3' => 'TKL', 'name' => 'Tokelau'],
			['id' => 215, 'iso_code' => 'TO', 'iso_code3' => 'TON', 'name' => 'Tonga'],
			['id' => 216, 'iso_code' => 'TT', 'iso_code3' => 'TTO', 'name' => 'Trinidad and Tobago'],
			['id' => 217, 'iso_code' => 'TN', 'iso_code3' => 'TUN', 'name' => 'Tunisia'],
			['id' => 218, 'iso_code' => 'TR', 'iso_code3' => 'TUR', 'name' => 'Turkey'],
			['id' => 219, 'iso_code' => 'TM', 'iso_code3' => 'TKM', 'name' => 'Turkmenistan'],
			['id' => 220, 'iso_code' => 'TC', 'iso_code3' => 'TCA', 'name' => 'Turks and Caicos Islands'],
			['id' => 221, 'iso_code' => 'TV', 'iso_code3' => 'TUV', 'name' => 'Tuvalu'],
			['id' => 222, 'iso_code' => 'UG', 'iso_code3' => 'UGA', 'name' => 'Uganda'],
			['id' => 223, 'iso_code' => 'UA', 'iso_code3' => 'UKR', 'name' => 'Ukraine'],
			['id' => 224, 'iso_code' => 'AE', 'iso_code3' => 'ARE', 'name' => 'United Arab Emirates'],
			['id' => 225, 'iso_code' => 'GB', 'iso_code3' => 'GBR', 'name' => 'United Kingdom'],
			['id' => 226, 'iso_code' => 'US', 'iso_code3' => 'USA', 'name' => 'United States'],
			['id' => 227, 'iso_code' => 'UM', 'iso_code3' => 'UMI', 'name' => 'United States Minor Outlying Islands'],
			['id' => 228, 'iso_code' => 'UY', 'iso_code3' => 'URY', 'name' => 'Uruguay'],
			['id' => 229, 'iso_code' => 'UZ', 'iso_code3' => 'UZB', 'name' => 'Uzbekistan'],
			['id' => 230, 'iso_code' => 'VU', 'iso_code3' => 'VUT', 'name' => 'Vanuatu'],
			['id' => 231, 'iso_code' => 'VE', 'iso_code3' => 'VEN', 'name' => 'Venezuela'],
			['id' => 232, 'iso_code' => 'VN', 'iso_code3' => 'VNM', 'name' => 'Viet Nam'],
			['id' => 233, 'iso_code' => 'VG', 'iso_code3' => 'VGB', 'name' => 'Virgin Islands, British'],
			['id' => 234, 'iso_code' => 'VI', 'iso_code3' => 'VIR', 'name' => 'Virgin Islands, U.S.'],
			['id' => 235, 'iso_code' => 'WF', 'iso_code3' => 'WLF', 'name' => 'Wallis and Futuna'],
			['id' => 236, 'iso_code' => 'EH', 'iso_code3' => 'ESH', 'name' => 'Western Sahara'],
			['id' => 237, 'iso_code' => 'YE', 'iso_code3' => 'YEM', 'name' => 'Yemen'],
			['id' => 238, 'iso_code' => 'ZM', 'iso_code3' => 'ZMB', 'name' => 'Zambia'],
			['id' => 239, 'iso_code' => 'ZW', 'iso_code3' => 'ZWE', 'name' => 'Zimbabwe'],
		])->run();

		$this->table('countries')
			->addColumn('is_others', 'boolean', ['nullable' => false, 'default' => false])
			->update();

		$this->database()->insert('countries')->values([
			['id' => 240, 'iso_code' => '--', 'iso_code3' => '---', 'name' => 'Others', 'is_others' => true],
		])->run();
	}

	public function down(): void
	{
		$this->table('countries')->drop();
	}
}
